### ISSUE TITLE
404 /__api__/appzip error

### ISSUE THREAD

**Issue by earlred** [phonegap/phonegap-app-desktop#360]
I just got this error after successfully using for a full day.

I tried the following to fix the issue:
-Updated the phone gap CLI.
-Removed the IOS app and reinstalled.
-Removed the phone gap desktop app and reinstalled>updated to the most recent version.
-Changed the port to 3001 then back to 3000.
-Checked localhost:3000 which loaded properly on the browser.
Error still persists when using the IOS app.

![phonegap_and_issues_ _phonegap_phonegap-app-desktop](https://cloud.githubusercontent.com/assets/7470993/7716427/d973bfea-fe46-11e4-935d-c787fd6615d6.jpg)

![img_2869](https://cloud.githubusercontent.com/assets/7470993/7716465/3fe27c62-fe47-11e4-9990-7ed30f17ab53.PNG)

**Comment by holgertepper** [comment]
Hi ! 
I am facing the exact same problem since 3 hours on 2 Windows machines both showing the same problem as discribed above.

After weeks of devoloping the communication between my iPhone 4 and my WindowsPC just stopped for no reason from one to another minute.
After some checking reinstalled the "PhoneGap Developer App" in my iPhone 4S and my iPhone5, and i reinstalled the "PhoneGap Desktop Server" ( CLI )
!
 for Windows 7. 
I also created a new test project - App and Server cant connect.

What I do is:
Start Phonegap Server in Windows ( firewall off )
..... Listening on [LOCAL IP:3000]

Start Phonegap Dev. App on iPhone -> Press Connect 
...... it says "Downloading" ...4 secs "ERROR !" .. 2 secs "DOWNLOAD ERROR" and then it shows the message already postet by earlred above.

Phonegap Server Log says: 404 /__api__/appzip for everytime i try to connect.

![phonegaperror](https://cloud.githubusercontent.com/assets/12521745/7717844/729fdc42-fea8-11e4-9028-7d4aacba84a7.png)


I have no idead what the problem cound be, but since it happened in the described manner, i guess there must be some external server causing the problem. 

Any help is well appreciated. Kind regards from Germany

**Comment by DennisVanRijswijk** [comment]
Same problem here, "Phonegap Desktop App" update to 0.1.7 (beta) has not solved the problem.

**Comment by hermwong** [comment]
Which version of the PhoneGap Developer App are you guys using?

**Comment by DennisVanRijswijk** [comment]
Android: 1.5.2
iOS: 1.5.2

**Comment by holgertepper** [comment]
1.5.2

**Comment by hermwong** [comment]
related issue: https://github.com/phonegap/phonegap-app-desktop/issues/358

**Comment by hermwong** [comment]
Are you using it on a corporate network or a firewall? 

The update to the `connect-phonegap` dependency used by PhoneGap Desktop has changed the way that apps are streamed from the PhoneGap Desktop to the PhoneGap Developer App; it now zips the app that you want to preview and streams the zip file over to the PhoneGap Developer App.

If you're behind a corporate network or you have a firewall blocking the streaming of zip files it will cause this error.

I see this error when attempting to pair the PhoneGap Desktop 0.1.67 and PhoneGap Developer 1.5.2 (iOS) on the network at the Adobe offices, however if I create a mobile hotspot with my mobile phone or try to pair while on my home network, I am able to pair successfully.

**Comment by DennisVanRijswijk** [comment]
@hermwong -> it's my home office without a corporate network. The firewall is turned of on my desktop and router. Still having the download error message on the devices (Android & iOS). 

The problem started when i updated "PhoneGap Devlopers App" on my devices to version 1.5.2.
After reading the blog (http://phonegap.com/blog/2015/05/19/phonegap-app-desktop-0-1-7/) i also updated the "PhoneGap Desktop App" to version 0.1.7. for solving the download problem, but it did not solved the download problem.

**Comment by hermwong** [comment]
@DennisVanRijswijk thanks for the info! It looks like we will need to investigate further to pinpoint the root cause of the issue.

**Comment by timkim** [comment]
Hi @DennisVanRijswijk 

I just tried on my windows machine with the `PhoneGap Desktop App@0.1.7` and `PhoneGap Developer App@1.5.2` and it works for me. Can you show us the output on your server log?

**Comment by taspapas** [comment]
Hi,
I have exactly the same problem since yesterday. I assume after an update.
I am using PhoneGap Developer 1.5.2 , PhoneGap Desktop 0.1.3-0.1.5, updated phonegap CLI.
I could n't try new  PhoneGap Desktop editions since I am still on win32...

Are you planing to release a win32 bug fix?
thanks

**Comment by hermwong** [comment]
Hi @taspapas,

PhoneGap Developer 1.5.2 requires PhoneGap Desktop 0.1.7.

**Comment by leandrorope** [comment]
Hello,

I'm using version phonegap -version = 5.0.0-0.27.0 and with the latest update for Google Play. I'm having the same mistake.

**Comment by hermwong** [comment]
@leandrorope are you serving from the PhoneGap-CLI and trying to preview with the PhoneGap Developer app?

**Comment by leandrorope** [comment]
Yes

**Comment by hermwong** [comment]
@leandrorope try updating to PhoneGap-CLI 5.0.0-0.28.0 it uses the updated `connect-phonegap` 0.16.0 module which is required for PhoneGap Developer 1.5.2.

**Comment by DennisVanRijswijk** [comment]
Hi @hermwong & @timkim,

Here are the sreenshots of what i'm see on my desktop and mobile devices:

https://cloud.githubusercontent.com/assets/3160325/7786936/81943fac-01ed-11e5-9a32-28925b9b83bd.jpg

**Comment by danielpsf** [comment]
I've the same problem with cli (5.0.0-0.27.0) on Ubuntu (14.04).

It got solved by doing an ```sugo npm update -g phonegap``` and updating to **5.0.0-0.28.0**.

**Comment by opportunex** [comment]
Same problem here.  It never said "Downloading..." before when trying to connect.  It would say "Connecting...".  I've been using it for months without incident, suddenly last night this happened.  Tried all of the suggestions in this thread, still no luck.

**Comment by opportunex** [comment]
Downloaded the update here: http://phonegap.com/blog/2015/05/19/phonegap-app-desktop-0-1-7/ and it worked (after reinstalling: npm update -g phonegap)... not sure if the reinstall was necessary or related. But after downloading and installing the update from the URL above, the problem was fixed.  

They must have changed the way the desktop server functions, because now it compiles the application via .zip and then downloads it to the phone and extracts and serves it up.  This decreases the system resources on the desktop considerable, but no longer allows for instantaneous "live" updates to be pushed to the phone. You have to start and stop the app on the phone in order to see your changes - very irritating, but maybe less so than the 40% CPU spikes the last version caused... we shall see.

**Comment by cwsterling** [comment]
I'm running into this issue. I'm on a corporate network. Was working until my phonegap developer app on my phone updated.  I've downloaded the latest phonegap desktop, I have the latest app as far as I can tell.

I even added an exception for port 3000 in my local firewall to see if that would help and that didn't help.

Let me know if I can give any more information

**Comment by alexcroox** [comment]
I'm getting this with Cordova CLI, or am I in the wrong place?

**Comment by alexcroox** [comment]
OK fixed by install `phonegap` CLI tools alongside `cordova`. God this phonegap/cordova confusion is a mess...

**Comment by BrunoGiubilei** [comment]
Hey i fixed this updating the phonegap using
sudo npm update -g phonegap

working now on kubuntu 14.04 LTS and Android 4.3 with the app most recent

**Comment by superkew** [comment]
The updates have helped but I am still getting a problem when serving.

events.js:72

throw er; // Unhandled 'error' event

^

Error: EMFILE, open 'E:\.....\37541.png'

**Comment by BrunoGiubilei** [comment]
su

**Comment by BrunoGiubilei** [comment]
open your project in chrome and press f12 and tell me what the error in line 72

**Comment by superkew** [comment]
It doesn't pick it up - chrome debugging shows no errors. I don't have an events.js file in my project.

**Comment by superkew** [comment]
I do all my coding using chrome, and then I use the phonegap serve feature to test plugin specific code because that obviously doesn't work in chrome.

**Comment by BrunoGiubilei** [comment]
try put a <script src="events.js"></script> in its latest index of code line

**Comment by superkew** [comment]
Thanks Bruno, I'll give it a try when I get home from work this evening.

**Comment by gostosinhadapraia** [comment]
Please, Phonegap, release the version for win 32 bit as far as you can.
I had to stop my projects and this is bad for my business :(

**Comment by superkew** [comment]
Is there a special way to debug the compiles phonegap app in Chrome? Referencing the js file does the same as I expected - just does a failed get. The same way cordova fails to get when running the app in chrome.

I tried changing the path to a shorter path and that doesn't work either.

Both the CLI and phonegap desktop app break. 

Versions verified to be the latest according to the blog.

**Comment by superkew** [comment]
I have found a work around for now. It is possible that the app doesn't support the number of images I have, as I am storing mapping tiles in the app, and the count is around 4200 images.

**Comment by BrunoGiubilei** [comment]
did you try a build.phonegap.com site? take a look and submit your code,
this site compile your code in formats for Android, Iphone and Windows.
When compilation is finish you can get the log files from errors
Em 30/05/2015 17:42, "superkew" <notifications@github.com> escreveu:

**Comment by superkew** [comment]
Phonegap build works fine. The only problem is the local serve feature. I have a work around for now so I'm fine.

Thanks for the help.

**Comment by hermwong** [comment]
@taspapas @gostosinhadapraia 

Win32 version has been added to the 0.1.7 release: https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.1.7

**Comment by christiansakai** [comment]
I am still encountering this issue.  Updated phonegap cli, updated cordova, also updated phonegap desktop app and updated phonegap app in IOS. Also did the same thing on Android.  Still doesn't work.

**Comment by hermwong** [comment]
Just a few notes about this issue:

- PhoneGap Desktop users do not require the PhoneGap CLI
- If you're using PhoneGap CLI to serve to the PhoneGap Developer App you require the following versions: 
  - PhoneGap CLI `5.0.0-0.28.0` or newer
  - PhoneGap Developer App `1.5.2` or newer
-If you're using PhoneGap Desktop App to serve to the PhoneGap Developer App you require the following versions:
  - PhoneGap Desktop App `0.1.7` or newer
  - PhoneGap Developer App `1.5.2` or newer
- firewall or anti-virus software need to be disabled or be configured to open the port being used
- being on a corporate network can cause this issue to occur
- if your project contains a lot of files it can cause this issue to occur

The issue is being caused by a bug in the `connect-phonegap` module which is used as a dependency by the PhoneGap Desktop App and PhoneGap Developer App. We are currently looking into the issue and hope to have it resolved soon.

**Comment by jw8** [comment]
I'm having the same problem, exactly as others have described it. 

Everything was fine earlier today, then I suddenly got the "Unable to download archive..." error. I followed all the recommended procedures -- updated everything, etc. -- then it worked...but only one time. It wouldn't auto-update when I made a change to a file, so I restarted the app, and now it's giving the same error again. My project is 16.2MB.

**Comment by mwbrooks** [comment]
@jw8 I've had a little luck in reproducing the scenario that you've had on both an iPhone 6 and Nexus 5 (Android 5.1). What operating system are you using? Thanks!

**Comment by jw8** [comment]
@mwbrooks Thanks for the quick reply.

* Windows 8.1 64-bit.
* iPad (3rd Generation, 32GB); iOS 8.3.
* Latest version of the Phonegap iOS mobile app.
* Phonegap CLI 5.0.0-0.28.1
* Phonegap Desktop App v0.1.7

Here's some additional info: 

I've found that auto-update does work sometimes -- but not other times -- and that it takes far longer now for the auto-update to kick-in than it did with the previous version of the desktop app/mobile app. So it's a matter of waiting a long time for it to update, then finally getting frustrated and restarting the app (knowing that it might not start up again). 

I've also found that the iOS mobile app's failure to load is intermittent; I was able to successfully use it for much of the day today, but now it has inexplicably stopped working again (giving me that same error alert already described).

While it might not necessarily belong on this thread, I'll also mention that since these new updates have taken place, when I load a JSON file via a pure-javascript XMLHttpRequest(), the file IS successfully loaded -- but returns a status of "0". I don't know what that means exactly, but I know the updates supposedly addressed some AJAX issues, so I'm curious what that's all about.

Thanks again!

**Comment by r2rapps** [comment]
Same error for me with below version in MAC 
phonegap -v
5.0.0-0.28.1
cordova -v
5.0.0

**Comment by r2rapps** [comment]
After update my DESKTOP APP version with "PhoneGap Desktop Beta 0.1.7", problem resolved.

THANKS to Team.

**Comment by theogray** [comment]
Having looked through all the comments I'm guessing we have the same issue and it's possibly related to having quite a lot of files (1,138) in the `www/` folder? Previous releases of the (Windows) Desktop and (iOS) Developer apps (before appzip) worked fine without issue. I tried reinstalling last Thursday (including removing the old Desktop files and using the full installers rather than just copying the Desktop App files into place) with no joy. Have also tried with both 64-bit and 32-bit versions of Desktop 0.1.7 (currently have 32-bit installed).

Phonegap Developer App errors (almost) immediately after tapping Connect as per the screenshots above.

Phonegap Desktop App shows `200 /__api__/appzip` in Server Log.

When calling `http://localhost:3000/__api__/appzip` via a browser, the resulting appzip.zip file contains 22 bytes: "PK" followed by `ENQ`(0x05), `ACK`(0x06) and then 18 `NUL` characters.

If I call `http://localhost:3000/` from Chrome with Ripple enabled I get individual files returned as requested, and then if I make a subsequent call to `http://localhost:3000/__api__/appzip` it sometimes works, producing a 9MB ZIP file. If this happens, then the Developer App is usually able to start running the app although over the past 7 days I've not managed to get beyond our splash screen before the log starts showing requests to `/__api__/autoreload` and Phonegap Developer then doesn't appear to get round to raising `deviceready`.

More often than not, loading `http://localhost:3000/` with Ripple enabled appears to cause the Desktop App to stop responding to any other requests for a minute or so and when it does start responding again then it goes back to returning the 22 bytes explained above.

I'm guessing from some of the responses you expect this to be fixed in 0.1.8; are there any thoughts on a release date for that or 0.1.8 Beta?

**Comment by teklifeinfo** [comment]
I have tried the desktop app 0.1.7 and the cli app 5.0.0-0.28.1, I still get the same error.

**Comment by jw8** [comment]
Here's my server log. Each "200 /__api__/autoreload" represents 2-3 seconds of wait time. Note that even after successfully loading, it continues to print out "200 /__api__/autoreload". This is no fun.

HERE, I'VE CHANGED A FILE (WHICH IT ACKNOWLEDGES), BUT IT CONTINUES CHOKING: 
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
undefined download error
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
SINCE IT STILL HASN'T LOADED, I CHANGE A FILE AGAIN (WHICH IT ACKNOWLEDGES AGAIN), AND CONTINUES:
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
undefined download error
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
ANOTHER FILE CHANGE HERE, AND:
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/appzip
200 /__api__/autoreload
HERE, IT'S FINALLY SUCCESSFULLY LOADED, BUT CONTINUES LIKE THIS:
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload
200 /__api__/autoreload

**Comment by giorgosart** [comment]
Is there a temporary solution for this?

**Comment by theogray** [comment]
I have tried a number of combinations today including having just 3 files in the `www/` folder - `config.xml`, `index.html` and `icon.png` - and still the request for the ZIP was returning the 22 bytes from my previous reply. So I gave in and started Process Monitor.

When loading from a project created by the latest Desktop app, Phonegap.exe successfully accesses `C:\App\www` and the ZIP is returned correctly. When loading with the 3 test files in `www/` Process Monitor shows Phonegap.exe failed to access `C:\App\www\www` with a `NAME NOT FOUND` error.

In a new project created by the Desktop app, you have `config.xml` in the root rather than in `www/` so I've tried copying our `config.xml` back to the root. This fixes the problem of the ZIP not being returned, but now deviceready was not being fired. I then spotted that the project created by the Desktop app references `cordova.js` rather than `phonegap.js` so tried updating that too. Finally the app runs :relieved:

So the changes I had to make so our app would run in the current iOS Phonegap Developer App were:
1. Copy `config.xml` into the root folder that Phonegap Desktop is watching (we appear to need it in `www/` as well for Ripple to work properly and for a valid iOS build via Phonegap Build).
2. Change `<script src='phonegap.js'>` to `<script src='cordova.js'>` in `index.html`.

**Comment by DennisVanRijswijk** [comment]
@theogray, Thanks a lot for your research and feedback.
 
Moving the config.xml file from the "www/" folder into the root folder of the project solved the download error! My phonegap / cordova script tag was already correct configured and is <script src='cordova.js'>.

**Comment by blackpenpress** [comment]
I'm also getting this after a file has changed.

200 /api/autoreload
undefined download error

desktop version 1.7 and android app 1.5.4

config.xml is already in the root folder and set to cordova.js in index.html

**Comment by ThatoMokhomong** [comment]
I managed to make it to work, for android users go to settings -> application manager -> phongap and then clear cache and data

**Comment by blackpenpress** [comment]
thanks @ThatoMokhomong, unfortunately that didn't make a difference in my case. I'm using a Galaxy S4 running lollipop.

**Comment by Sanafan** [comment]
Same here, nothing works. No zip file found.

**Comment by TLMcode** [comment]
@blackpenpress did you ever fix the issue? I'm having the same problem on Galaxy S6. Any help is greatly appreciated.

**Comment by blackpenpress** [comment]
@TLMcode no, I'm afraid I didn't. It's working for me on iphone, so it seems to be the galaxy that's having trouble rather than the desktop app/CLI.

**Comment by r-luna** [comment]
Same issue here, HTC One M8 running Android 5.0.2, Windows 10. Cordova CLI 5.2.0, Developer App 1.5.4

AVG Disabled, Dev App cache cleared, firewall disabled....

cordova serve continues to show 404 /__api__/appzip

http://localhost:8000/ shows me a page with a Package Meta Data heading and a platofrm directory tree.

I'm thinking ti would be nice to be able to select either the gzip option or the older option. I;m late to the party so I dont have pre-gzip experience but if it used to work.....

**Comment by lucassch** [comment]
Same issue here, Android 4.4, Windows 10, Phonegap Desktop 0.1.2

**Comment by hermwong** [comment]
@lucassch Upgrade to the latest [PhoneGap Desktop 0.1.11](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.1.11); version 0.1.2 doesn't work with the latest PhoneGap Mobile App.

**Comment by lucassch** [comment]
@hermwong: upgrade to the latest version fixed the issue. Thanks!

**Comment by 11plustwo** [comment]
I'm on a mac using a virtual machine for windows (VMWare) and my issue was solved when I changed the VM's network settings so the VM appears as a separate device on the network. As in, they don't share a local IP.

**Comment by simar88** [comment]
I have the same issue, and i would like to know if the problem is only the fact that I'm using **Cordova CLI** instead of **Phonegap CLI**.
Thanks in advance! :)

**Comment by hermwong** [comment]
@simar88 

Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by ivanssa** [comment]
Thanks I used `npm update -g phonegap` and everything was resolved ...
