### ISSUE TITLE
Error message: Unable to download archive from the server...

### ISSUE THREAD

**Issue by ireichert** [phonegap/phonegap-app-desktop#370]
Please upgrade the PhoneGap CLI...
I am running the newest desktop app (0.1.1)  and the newest mobile app. 
Network settings are fine.
Any suggestions?
Thanks.

**Comment by hermwong** [comment]
duplicate of https://github.com/phonegap/phonegap-app-desktop/issues/360

**Comment by ireichert** [comment]
Hi Herm,

Thanks for the reply. I really appreciate your help.

Do I have to update the Phonegap CLI by using the command line? How do i do it?  Does that mean that I can't use the desktop app to create a new phonegap project?

Thanks.
Isabel
________________________________

**Comment by hermwong** [comment]
The PhoneGap CLI is not required for the PhoneGap Desktop App, the issue that you're experiencing is an issue with the connect-PhoneGap module which is a dependency in the PhoneGap Desktop App, PhoneGap CLI and PhoneGap Developer App.

Does your project contain a lot of files?

We're currently working on a fix for the connect-PhoneGap module.

**Comment by ireichert** [comment]
Wonderful. I am a teacher using phonegap in my curriculum and a fix would really help.
Do you have a timeline?

Best,
Isabel
________________________________

**Comment by hermwong** [comment]
This issue is currently our top priority. We're currently looking at the best way to resolve it but don't have a timeline yet.

**Comment by mwbrooks** [comment]
Hi @ireichert, I'm trying to collect more information about each person's environment to better reproduce the issue. What operating system version (Windows 7, OS X, Linux, etc) and phone platform (iOS 8, Nexus 5 with Android 5.1, etc) are you using? Thanks!

**Comment by ireichert** [comment]
Hi Michael,

I am running Yosemite 10.10.2 on a mac and my testing device is a a Samsung Note2, 4.42 android.

I installed the newest phoneGap desktop app and the mobile app.

Would you like me to install android 5 and try again?

Thanks so much!
Best,
Isabel
________________________________

**Comment by mwbrooks** [comment]
Hi @ireichert, thanks for the info! I don't believe installing Android 5 will solve the issue.

If you have a spare moment, would you mind trying this test:

1. Start the PhoneGap Desktop app
2. Open Chrome on your Android device
3. Navigate to: `10.0.1.6:3000/__api__/appzip`
  - where you replace `10.0.1.6` with the IP address listed in the PhoneGap Desktop app
4. You should phone should download a ZIP file
5. If the download fails, please check the console in the PhoneGap Desktop app (left sidebar, little window icon)
  - Do you see a `200 /__api__/appzip` or `404 /__api__/appzip` or something else?

What we are trying to do is establish that your phone can connect properly to the Desktop app and download the zip. 

Thanks!
Michael

**Comment by felipelvira** [comment]
Hi @mwbrooks , 

I'm facing the same problem as @ireichert.
Operating system :
-Windows 7 ultimate 64 bits
Phone Platform :
-Android 5.0.2 on HTC One m7

I tired doing the test as you said and i got this messages :
`<404 /__api__/appzip>`

Thanks, 
Felipe

**Comment by Colkerr** [comment]
I have just installed desktop and mobile to windows 7 PC. Mobile is Android. I'm trying to run the appSample, following the tutorial. So I have not added any files or done anything other than follow the instructions in the Getting Started tutorial.

**Comment by ireichert** [comment]
Hi Michael,

I am getting a "Cannot GET/__api__appzip" error.
________________________________

**Comment by ireichert** [comment]
Hi Michael,

I neglected to send you the console log from the desktop app:
listening on <myIPhere>:3000
404/__api__/appzip
404/__api__/appzip

myIPhere is my IP address.

My phone app displayed the following error message:
Cannot GET/__api__/appzip

I hope this helps.
Best,
Isabel
________________________________

**Comment by mwbrooks** [comment]
Hi @ireichert,

Can you check the version of your PhoneGap Desktop App? You can do by clicking the lefthand sidebar `? -> About`.

I've noticed that a number of developers are using an older version of the PhoneGap Desktop App (`< v0.1.7`). These versions are incompatible with the latest Desktop app.

Cheers,
Michael

**Comment by ireichert** [comment]
Thanks, Michael. That did the trick.

Just a suggestion, you might want to make it a bit easier for people to find the newest version of the desktop app. I was under the impression that 0.1.2 was the latest release (since that's what is discussed on the phoneGap blog).

Thanks so much, again.
Best,
Isabel
________________________________

**Comment by mwbrooks** [comment]
Awesome @ireichert!

I hear ya. We still consider the PhoneGap Desktop App as a beta product. However, a few releases back we added in-app upgrade notifications. The most recent version also added auto-updates, so you should be notified of available updates and the app will upgrade itself.

Thanks again for pushing through this issue!

**Comment by mahesh8488** [comment]
I am using v0.1.8, but still facing the issue. Is it not resolved yet ?

**Comment by kayyyy** [comment]
I have the same Issue. I am running v0.1.8 on my Mac and the latest Version on my iPhone. 
Still getting the error.

![image](https://cloud.githubusercontent.com/assets/8193345/9156273/ad399958-3ed4-11e5-80e1-e14ad46b8bbd.png)

And on my phone "unable to download archive from the server".

**Comment by joshuairl** [comment]
My appzip downloads but it's only 30 bytes... very strange.

**Comment by joshuairl** [comment]
Scratch that, 22 bytes.

**Comment by joshuairl** [comment]
www directory was a symlink... wasn't working with symlink...
Now it just says "Downloading..." my appzip is only 9mb.  Not sure...

**Comment by JuanCarlosNulo** [comment]
I had the same problem... i resolved it desinstalling the application and then reinstalling it but changing the .exe's name...

**Comment by Rafay-Qureshi** [comment]
Hello Guys, found a Solution:
If you are having errors while connecting to PhoneGap via Mobile like:
- Unable to download archive from the server 
or
- Unable to connect properly to the server...
It might be occuring because of your Firewall, which is turned ONfor Private or Public.

I SOLVED this problem by turning Windows Firewall OFF, it works like a charm.
- Suggestion :  I think that turning off Firewall completely is not a good idea, rather it will be better to just Turn off Firewall for PhoneGap Desktop App.
You can do do this by :
- Open firewall options 
- "Allow an app or feature through Firewall" 
- Select PhoneGap Desktop App (Add it yourself if its not there, It will appear by name "Electron" after you add it)
- Allow access through Public & Private (tick check boxes).
- Try entering your correct Server Address on Mobile App e.g. (192.168.1.3:3000)
& It should work. Hope this helps others.

**Comment by ayyazzafar** [comment]
@Rafay-Qureshi You are awesome. You saved a lot of time. Your solution worked for me like charm.

Thanks a lot

**Comment by 11plustwo** [comment]
I'm on a mac using a virtual machine for windows (VMWare) and my issue was solved when I changed the VM's network settings so the VM appears as a separate device on the network. As in, they don't share a local IP.

**Comment by ahmetGur** [comment]
@Rafay-Qureshi You are awesome!!!. You saved a lot of time. Your solution worked for me like charm.
Thanks a lot man!!!

**Comment by Reispar** [comment]
Guys, please help me out.  m still receiving Application Error :  file://data/data/com.adobe.phonegap.app/files/phonegapdevapp/www/index.html on my Phonegap mobile app

**Comment by hermwong** [comment]
@Reispar can you provide a screen shot and the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by Reispar** [comment]
1. V0.3.5 Desktop version
2. V1.7.2 mobile version
3. Techno  / OS (mobile phone spec, see attached photo)
4. WINDOWS 7 Ultimate
5. HOME
6. NO Proxy
7. HP Desktop v185ws /Widows firewall on (public networks) / Kaspersky
v14.0.0 / disk encryption off
8. No
9. No
10. No
