### ISSUE TITLE
app status "downloading" and wont connect

### ISSUE THREAD

**Issue by sashabelov** [phonegap/phonegap-app-desktop#396]
Server connection is good, i can reach server from safari on my ios6 but cant connect to it from application, after i put ip and tap connect its show me a message "downloading..." and freeze forever

any suggestions?

**Comment by hermwong** [comment]
Which versions of the PhoneGap Desktop App and the PhoneGap Developer App are you using?

**Comment by sashabelov** [comment]
desktop is 0.18
phone app is 1.5.4

13.07.15 20:57, Herm Wong пишет:

**Comment by hermwong** [comment]
Looks like you have the latest versions of both apps.

Do you have firewall / AV software on your computer? Are you connected to a corporate network?

How big is your app?

**Comment by sashabelov** [comment]
No I don't have any of them, it's 4g router, and two devices connected, my iPhone 5 with ios 6 and MacBook Pro with Yosemite.
I didn't upload app to server, and it is perfectly load default phonegap page in safari app on iPhone, but phonegap app is freezing with status "downloading..." After I put IP and tap connect


Sent from Mail.Ru app for iOS

**Comment by schakra19** [comment]
I am facing the same issue. I have phonegap desktop version 0.1.8 and trying to connect it from iPhone 6 running iOS 8.3

**Comment by hermwong** [comment]
We've found that this issue is usually solved by making sure the following criteria are met:

1. disable firewall and AV software on your computer
1. make sure your router/network doesn't have a hardware firewall, if it does either disable it or configure it to allow traffic on the port that PhoneGap Desktop is using to serve (usually this is on a corporate network and you won't have the ability to change the config, if that's the case use a non-corporate network)
1. make sure that both your computer and mobile device are connected to the same network
1. make sure that you are using the latest versions of PhoneGap Desktop and the PhoneGap Developer apps

**Comment by sashabelov** [comment]
how do you read my answers?
1) never installed an firewalls or network security software on this 
MAC, its new yosemite without any firewall or antivirus
2) it is simple mobile 4g router that doesnt have an firewall and all 
security options are disabled. as i said before - i can connect to the 
ip and port in browser on iphone and can see the server. there is no an 
port or ip address restrictions in network
3) im sure
4) im sure

22.07.15 3:47, Herm Wong пишет:

**Comment by daivd-barr** [comment]
Hi,

I have the exact same issue. This issue has also been reported on the developer-app issue section (https://github.com/phonegap/phonegap-app-developer/issues/306)

Everyone seems to have started having this issue in the past 7 weeks. I upgraded the developer app to the latest version (1.5.4) a few days ago and it has worked fine until today, where the app is stuck on the "downloading..." screen.

I used the developer desktop and app yesterday without trouble, there has been no change to any of my network settings, but for some reason today I have this issue.

I have tried uninstall and reinstalling the developer app, rebooting my iPhone, different server addresses and I have upgraded the desktop app from 0.1.7 to 0.1.8 (latest version at time of writing), all without any luck.

I am using:
Desktop: 0.1.8
Developer App: 1.5.4

If you need any further information please ask?

Thank you.

**Comment by hermwong** [comment]
Have you tried using the PhoneGap CLI and seeing if this issue occurs?

**Comment by SpikedCola** [comment]
I am having the same issue. Using an iPhone 4 w/ iOS 6.1.3 and "PhoneGap Developer" app version 1.5.4

I've tried both PhoneGap Desktop v0.1.9 and CLI ('phonegap serve'). 

The app does not connect to either. In fact, I see no WireShark traffic at all when I hit "Connect". Nor do I see any log hits in either app.

However, as with @sashabelov , the server responds if I view the correct IP & port in Safari. I see log hits as expected.

To me this feels like an issue with the PhoneGap Developer app. I can enter "1.2.3" as the IP address and it will show "Downloading..." with no error prompt

**Comment by vardas-bill** [comment]
I am also getting this problem having just installed the latest versions of Phonegap Desktop and Phonegap Developer App. Can't get past the 'DOWNLOADING' message.

**Comment by hermwong** [comment]
@vardas-bill do you have a project that contains a lot of files or is very large in size (MB)?

**Comment by hermwong** [comment]
Latest versions of PhoneGap Desktop 0.1.10 and PhoneGap Developer 1.5.5 might resolve the issue for some of you.

**Comment by vardas-bill** [comment]
The project is @4MB.

I am using the latest versions of PhoneGap Desktop and PhoneGap Developer.

**Comment by vardas-bill** [comment]
I have got a bit further in as much as I now get an error on PhoneGap Developer "Unable to properly unzip archive"

**Comment by hermwong** [comment]
Are you using a virtual machine or do you have multiple virtual network adapters on your computer?

If so you could try [disabling](https://github.com/phonegap/phonegap-app-desktop/issues/356#issuecomment-145995007) the virtual network adapters.

**Comment by sashabelov** [comment]
No, I'm not 
No virtual adapters or machine 

Sent from Mail.Ru app for iOS

Среда, 14 октября 2015 г., 21:32 +0600 from Herm Wong  <notifications@github.com>:
Are you using a virtual machine or do you have multiple virtual network adapters on your computer?
If so you could try  disabling the virtual network adapters.

**Comment by hermwong** [comment]
We're still investigating this issue. I'll provide an update when we have any new details. Thanks for your patience.

**Comment by moderactif** [comment]
thank you @hermwong

**Comment by avneeshv** [comment]
I see the same problem with phonegap CLI 5.3.6 on windows 7. I can access the link from the same machine through browser. But somehow can not access it from other machines (neither phone browser/Phonegap app neither windows browser) in the same network. I have ensured that there are no firewall rules blocking the ports.

**Comment by hermwong** [comment]
We're having a difficult time reproducing this issue. It seems like this issue doesn't happen for all of our users. Could you provide the following information so that we could try to pinpoint the root cause of the issue?

1. PhoneGap Desktop version / PhoneGap CLI version
1. PhoneGap Mobile App version
1. Mobile devices & Mobile OS version
1. Computer OS version
1. network type (home/corporate)
1. computer / network security (firewall / anti-virus / disk encryption)
1. are you using VMs on your computer?
1. do you have multiple network adapters (or virtual network adapters)
1. number of files in your mobile app
1. size of your mobile app

**Comment by sashabelov** [comment]
1. Latest version
2. Latest version
3. iPhone 5 on iOS 6.1.4
4. Mac OS X Yosemite
5. Home network, 4G router modem
6. none of this software
7. no
8. no
9. just test phonegap page
10.  just standard test phonegap page

22.10.15 4:12, Herm Wong пишет:

**Comment by linkdmx** [comment]
SOLVED!
I realized the IP address was incorrect. I opened my "cmd" terminal, and typed "ipconfig /all" to find out my actual IP address (IPv4 address) was 192.168.1.72 (and NOT 192.168.41.1) . (There's plenty of ways to find out your current IP)
So I changed the address in my mobile app and it worked!

**Comment by hermwong** [comment]
@linkdmx was the PhoneGap Desktop App displaying 192.168.41.1 (the wrong IP address) in the status bar?

**Comment by rjohn0612** [comment]
Hi,
I'm very new to all of this, but I'm having a connection issue as well on Windows 8.1

Using desktop app PhoneGap (v0.1.11) and PhoneGap Developer app for iOS version 1.5.8 on iPhone 6. OS 9.0.2

I can connect via Chrome to the server at 10.127.127.1:3000 but the app never does.  It's always frozen at the " Downloading....... " screen.

Yes I am on the same wireless network and I did temporarily turn off my computer's firewall and anti-virus program as recommended above in a previous post.  I'm no expert but if I had to guess I'd say there is definitely some kind of issue with the phone app.

**Comment by roelleor** [comment]
For me, the PhoneGap app on my mac showed the wrong IP-address. (so the solution is to find your own ip address and add :3000)

**Comment by Jack600** [comment]
Same issue,

I pod touch Ios 6.1.6.

PhoneGap server installed in command line on two comptuer WIN10 wired on router, and WIN Vista on WIFI.

I can reach the server with Safari and download the __API__ zip with the IpodTouch, no connexion problem to server with all my stuff on the iPod but, the PhoneGap APP show "Downloading..." with no error prompt after i press connect.

Impossible to reach the two computers.
I seek IP conflict, no.
I tried with one computer shutdown.
I try to ping IP
All is on the same network
Latest version of all, but one installed with node,js LTS 4.2.2 and the other with node JS 5

I Hope this problem could be fixed !

**Comment by Wambosa** [comment]
i also have found that the app does not work . stuck on downloading...
1. Server log does not mention any kind of connection
2. same network
3. no firewall
4. one adapter
5. no antivirus
6. can connect via web browser (obviously won't work for real though)
7. Tried latest Desktop App v 0.1.11 and app 1.5.8
8. alos tried serving using CLI. same results.
9. conclusion: app is most likely the problem

**Comment by hermwong** [comment]
related to: https://github.com/phonegap/phonegap-app-developer/issues/351

**Comment by tasarsu** [comment]
same issue with ios 9.1 phonegap 5.3.8. 
It keeps saying downloading

**Comment by FreeFromItAll** [comment]
same here, ios 9.1 phonegap developer app 1.5.8 using cli on mac os 10.10. it just sais downloading all the time. I have checked the ip is right.

**Comment by kirill001** [comment]
Same issue. Windows 7 and android 4.1.2, "Hello world default application". 
I can download appzip through my pc browser (ip/__api__/appzip), but I can't do it with by mobile browsers (404 error). 
no antivirus, no firewall

**Comment by hermwong** [comment]
Working on resolving the issue with multiple IP addresses: https://github.com/phonegap/phonegap-app-desktop/issues/494

**Comment by kishangpatel** [comment]
same issue here - 
Anybody got any solution!!
Please share 
Thanks.

**Comment by sagars18** [comment]
My phonegap app in not connecting to my phonegap desktop..it shows me download error

**Comment by barrylachapelle** [comment]
Hey all. This was driving me nuts all day. One other thing to try that worked for me, reboot your router ;)

**Comment by jorisvanh** [comment]
Please let me know when this is fixed.

**Comment by gcpmendez** [comment]
wrong IP. Go to "cmd". ipconfig /all and see IPV4 address.

**Comment by jorisvanh** [comment]
My issue is solved:: I was on a corporate network. Added my phones MAC address to the exclusion list of the firewall.

**Comment by renatomestre** [comment]
Still have the problem... Setup: Win10 + PhoneGap CLI 5.4.0 + iOS 6.1.6 (10B500) on an iPhone 3GS.

On the iPhone's Safari, the route is accessible normally. Even auto refresh it does! But on the Developer App, remains the "Downloading" message.

**Comment by borjasanes** [comment]
I have the same problem... (lastest version of phonegap and phonegap developer app for ios)I have configured port forwarding, then I tried to connect my iphone and it didnt work.

**Comment by tauntdigital** [comment]
Just wanted to say I have had the same error on iOS and I've narrowed it down to my app having too many files (about 1700). When I remove the bulk of the files, it works again. It's also not dependent on the size of the files, just the actual number of them as I've tried it with fewer but bigger overall files and it works.

**Comment by vance** [comment]
Can confirm. too many files = won't load. they're not big files, just bootstrap and my bower libs.... what's the deal here?

**Comment by chrisgriffith** [comment]
Maybe you might want to add a build step to concatenate them into one file.
It could solve this issue, plus your performance later will be better.

**Comment by vance** [comment]
This is untenable. My app will have to bundle over 1,000 images.

**Comment by vance** [comment]
Is this a Cordova issue or a phone gap packaging issue?

**Comment by hermwong** [comment]
Neither. It's a performance issue with the previewing feature between the PhoneGap Desktop and the PhoneGap Dev App.

**Comment by panalgin** [comment]
PhoneGap CLI 0.4.3
PhoneGap App 1.7.6

I faced this issue. I tried everything, port forwarding, updating cli and app, reinstalling cli and app, restarting both pc and phone, uninstalling any suspicious networking application on pc etc. nothing solved it.

But I solved my case, It was very interesting though.
I sit and work 5-6 meters away from my router. The router is placed in another room in my house. Both my pc and phone connects to that router using WiFi. Although I can visit anywebsite including the phonegap cli-server via my chrome app in my phone, **it seems the connection's quality is not enough for phonegap app in my phone** to connect it by itself. When I walked near to my router, phonegap app sucessfully connected to my blank phonegap app. When I get a little far away from my router like 2-3 meters, although still I was able to watch videos on youtube without a pause, phonegap app gets stuck at downloading again.

That was my case, thought the devs would like to know it, thanks for the superb product.

**Comment by ScottBeeson** [comment]
Same problem as others, I had to use the bottom IP address:

![image](https://cloud.githubusercontent.com/assets/108358/26465261/336c2fca-4150-11e7-8a1b-ff29e0884952.png)

**Comment by cold2425** [comment]
Same problem as others, but i can fix it.
(Windows 7/10)
If u can try connection first time on the pc we can see 2 adresses. 
Now we are trying to connect on mobile phone we can se:
"downloading..."
"tap to cancel"
"downloading..."
"tap to cancel"
So...
1. Disable firewall and antivirus on the pc.
2. Close PhoneGap.
3. Run PhoneGap.
In my case after run PhoneGap, Windows show mi window:
![Image of Yaktocat](https://i.stack.imgur.com/HoviS.png)
I checked all checkboxes and press button "Allow access".

And i tried to connect on the phone. That's all. 

If any of you use windows then the problem may be with the firewall. With windows firewall, not an anti-virus firewall.

Good luck!

**Comment by disier** [comment]
Hi all,

I had the same issue. 

First I verified I was not a connection problem: I coud access the address (in my case 192.168.65.45:3000) from a web browser in my phone.

Then I realized that the index.html created by a 'Hello World" App created with Phonegap had some META tags in the HEADER, that were missing in the index.html of my App.

I copied those META to my index and everything works. The Phonegap Developer App downloaded and loaded my WebApp

`<meta name="format-detection" content="telephone=no" />

    <meta name="msapplication-tap-highlight" content="no" />

    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />

    <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src *" />`

**Comment by knurmi** [comment]
I had this issue but I've resolved it for me. Check what plugins you use. 

My app had a Bluetooth plugin and was failing to start with it off. As soon as I enabled it, the app started (though slower than android)

**Comment by serverfire** [comment]
I had this issue and i used another IP and this issue solved for me.

**Comment by pitininja** [comment]
I had the same issue: stuck on "Downloading / Tap to cancel" on the Android app while trying to connect PhoneGap server.

The issue was my antivitus / firewall (Eset) which was blocking the connection. I figured it out disabling the protection and trying again: it worked.

So it may be useful to check your antivirus (if you have one), try to disable it, and if it works, create a rule to allow PhoneGap connection.

**Comment by jinhale** [comment]
I'm using COM.ADOBE.PHONEGAP.APP: 1.8.4. It does the same thing. The wrong address is claimed to be current when the last on the list is the current/correct address.

**Comment by guberti** [comment]
programmer8872's solution worked perfectly for me. Only the last address (192.168.137.1) worked.

**Comment by shazinfosys** [comment]
make sure you are using same internet connection to your computer and mobile. or try mobile data On and connect mobile with USB and use mobile Data connection for your computer too, It will definitely works.

**Comment by christemple1** [comment]
There is a windows setting called "network discovery. Since you are connecting 2 devices on the same network it must be enabled. Control Panel\Network and Internet\Network and Sharing Center\Advanced sharing settings.
