### ISSUE TITLE
Phonegap Desktop App stuck on loading screen

### ISSUE THREAD

**Issue by Toxide** [phonegap/phonegap-app-desktop#739]
Windows 10 Pro
PhoneGap Desktop version 0.4.1
PhoneGap Mobile App version 1.7.6
home network
No proxy
No- Computer / Network security (firewall / anti-virus / disk encryption)
No- VMs 
I have an android virtual network adapter
No - Vpn

### Expected Behaviour
I expect the app to load into the main dashboard so i can view a phonegap project

### Actual Behaviour
Once i add a project to the desktop app all it displays is a white screen (Still on desktop app).

### Steps to Reproduce 
This happens every time i add a project t a fresh install of the Phonegap Desktop App. I have the same issues on my Windows 7 ultimate machine.

#### Error messages
This is a windows 7 Screen Shot
![windows7ultimate](https://cloud.githubusercontent.com/assets/23723088/20601638/82c6be0c-b251-11e6-97de-fcb4ecf73e3a.png)

Windows 10 Loading
![windows10loading](https://cloud.githubusercontent.com/assets/23723088/20601962/3211f25e-b253-11e6-89e0-4f8990be181b.png)

Windows 10 loaded
![windows10loaded](https://cloud.githubusercontent.com/assets/23723088/20601967/380694f8-b253-11e6-9e4e-a1accac1fe47.png)

**Comment by oldbk** [comment]
![2016-11-26_203242](https://cloud.githubusercontent.com/assets/6886009/20642478/de614c66-b420-11e6-853b-e4c41772a0a8.png)
same trouble, win 8.1

**Comment by surajpindoria** [comment]
Which method did you use to install the Desktop App, the installer or the zip? If you used the zip, there are additional steps required to get it setup correctly.

https://github.com/phonegap/phonegap-app-desktop#installation-for-windows

**Comment by oldbk** [comment]
PhoneGapSetup-win32.exe

**Comment by hermwong** [comment]
potential duplicate of #669

**Comment by hermwong** [comment]
I would suggest trying with your firewall and AV software disabled or configure them to allow PhoneGap Desktop to make external requests.

If the above suggestion doesn't work.

Can you try deleting the localStorage used by PhoneGap Desktop. This will remove your project from PhoneGap Desktop's cache, but will not remove your project from your computer.

make sure you have closed PhoneGap Desktop
delete the localStorage at the locations below.
On Mac: `~/Library/Application Support/PhoneGap/Local Storage`
On Windows: `C:\Users\<Windows User Name>\AppData\Roaming\PhoneGap\Local Storage`
restart PhoneGap Desktop

**Comment by Toxide** [comment]
I have installed the Latest exe file from the Phonegap Website. as oldbk mentioned above there version PhoneGapSetup-win32.exe.

I have removed all cache and localStorage  from my windows folders and once i add new folders the load screeen goes white and the desktop application stops working.

**Comment by TonyCelentano** [comment]
I am having exact same problem as OP. Latest version of Phonegap Desktop freshly installed on Windows 7 Ultimate. Tried adding Phonegap to firewall exception, tried disabling firewall, and also tried deleting the localStorage folder.

PhoneGap just spins and spins...and spins...and spins.

**Comment by damanmokha** [comment]
I am having same problem, i have windows 10, installed via exe, latest version, disabled firewall, no antivirus, deleted localstorage, still same problem, Any solution found yet?

**Comment by kweamod** [comment]
Installed version 0.4.3. Still having the same problem. Any news? Tried disabeling firewall and anti virus already, also cleared the local storage.

**Comment by Toxide** [comment]
I couldn't get that version working on my windows 7 ultimate so i ended up having to use simulators to check my app. Took longer to test but probably quicker than figuring out why it didn't work.

Have to tried installing a previous version.

**Comment by surajpindoria** [comment]
We have not been able to reproduce this issue on our end so it has made finding a solution very difficult. We just released a new version this week, 0.4.4, maybe that will help.

Another solution would be to use the phonegap-cli, you can do so by running `npm install -g phonegap` and then `phonegap serve` from your project directory. This will allow you preview your app on the mobile device.

**Comment by Vegardstoylen** [comment]
Hi
I fixed the problem by running the file "postInstall.bat" as administrator (locaded:PhoneGap-Desktop-Beta-0.4.4-win-1.zip\PhoneGap-win32-ia32\resources\app.asar.unpacked\bin)
This was in the zipfile: "PhoneGap-Desktop-Beta-0.4.4-win.zip" downloaded from https://github.com/phonegap/phonegap-app-desktop/releases 
Make sure the postInstall.bat file is finished running before running PhoneGap

As explained in the INSTALL-file

**Comment by JeffreyKrist** [comment]
Fixed for me for 0.4.4 on Mac by recursively set the file owner to myself on all project folders.

**Comment by smiffsoft** [comment]
Exactly the same here. I tried the Windows installer (0.4.4), and the ZIP method of installation with exactly the same result.  I also ran the postInstall.bat file as described in the ZIP instructions, but this made no difference whatsoever.

Windows 10, no firewalls or anti-virus running. Phonegap 0.4.4, no proxies or VPN, not in a VM.

**Comment by XaiNano** [comment]
Hi, after I run Phonegap Desktop App **as a administrator**, it worked for me.

**Comment by edoardo-reis** [comment]
Hi, 
I got the same problem.
Following the steps of hermwong I've noted that the path mentioned doesn't exist. Instead of User/<name>/AppData(...) ,I got this path --> C:\Users\**Default.migrated**\AppData\Roaming
There is no Phonegap file or folder inside. 

Any relation?

**Comment by surajpindoria** [comment]
Hi @edoardo-reis,

Have you tried right clicking "PhoneGap.exe" and then "Run as administrator" as suggested in the previous comment?

**Comment by edoardo-reis** [comment]
Hi @surajpindoria,

I did, but didn't work. I've tried all suggestions mentioned here, no success. 
There is any possibility of this problem be related to the last updates of windows 10?
By the way, I'm running my projects by the cli version.

**Comment by surajpindoria** [comment]
I can't be certain if this is related to Windows 10, unfortunately we are not able to reproduce this issue on our machines so it has been very difficult to try and solve.

And using the CLI is the best workaround in the meantime while we try and solve this issue.

**Comment by smiffsoft** [comment]
Just to confirm, I have tried running as user, as Administrator, completely deleting and reinstalling each time. I've worked in 3rd line support and development for many years and believe me I;ve exhausted every single avenue I can think of (but I'm sure some QA bod might find another one!).  Nothing fixed the eternal loading screen.

**Comment by setiabudhi-raymond** [comment]
Hi All,

I'm a newbie in mobile developer, and i face the same problem, 

OS : Wondows 10 Home 64 bit
Phonegap desktop ver : 0.4.4

Since i;m a newbie aqt first i'm so excited to learn mobile developer coding, but this problem really annoy me, is there any solution yet ? i tried all the solutions here, delete the local storage, run as administrator, run the postInstall.bat but still nothing happen the loading screen just keep spinning and spinning... and spinning....
Is it happen due to my windows is 64 bit, and the phonegap is 32 ? Thank you

**Comment by surajpindoria** [comment]
Hi @setiabudhi-raymond,

This should not be related to your computer being a 64 bit machine. Unfortunately we are unable to reproduce this issue on our machines so it has made debugging this very difficult. All we can do right now is gather as much info as we can to hopefully attempt to resolve this.

**Comment by sunnymtl** [comment]
I had the same problem. All above methods didn't work for me, but after I closed the Visual Studio Code (which worked in the same project), Phonegap worked again as usual (even if I opened the Code after).

**Comment by shahgidog** [comment]
Had the same loading spinner issue after installing 0.4.4 on windows 10.
Tried all advice I could find, nothing worked.
Fixed by:
- Uninstalling desktop app, removing every folder & file containing 'phonegap'
- Installed latest version of nodejs (6.1.1) & npm (5.3.0)
- Reinstalled desktop app

Now works perfectly.
Hope this helps someone.

**Comment by remagalot** [comment]
cmd
npm clean cache
cd C:\Program Files (x86)\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\bin
postInstall.bat
Open Phone Gap

This worked for me... maybe it can serve others well also?  =)

**Comment by cepm-nate** [comment]
npm cache clean

is the proper command. But even after doing that and running the postInstall.bat as admin (which downloads the PhoneGap CLI via NPM), I'm also still getting the loading spinner in the PhoneGap Desktop app. Both when running normally and running as admin. (Windows 10 x64)

Investigating with SysInternal tools right now.

**Comment by kavichezliyanr** [comment]
Execute below it worked for me .
postInstall.bat
Open Phone Gap

**Comment by bstreiss** [comment]
@remagalot's method worked for me, until postInstall.bat errored out.  Eventually discovered I had to add
`npm config set strict-ssl false`
then is all worked for me.

**Comment by drcrack** [comment]
Same problem. I'm 99% sure that's because I have no drive C:, but this drive is hardcoded somewhere in the app.

**Comment by adeyinkaroyal** [comment]
I had same problem with eternal spinner.
I solved it today by uninstalling phonegap, I then downloaded nodejs and installed it.
Then I installed phonegap and it worked perfectly.

**Comment by zerox1212** [comment]
It seems you must have `node.js` installed before PhoneGap. Without node PhoneGap deskotop never starts and the loading circle spins forever. The docs should be updated to state that node.js is required.

**Comment by aman-saggu-git** [comment]
This problem still exist on my side as well. i have reinstall phonegap. stilll problem exist. Is there any permanent solution for this. or this bug is a gift for us.

**Comment by raiffhigor** [comment]
Guys, i had the same issue but i installed node.js and after the phonegap desktop and it worked like other colleagues said in previous comments . Only to leave a feedback. Thanks in advance for colaboration.

**Comment by larbear** [comment]
Running the postInstall.bat file, in c:\program files (x86)\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\bin worked for me, however, I had to load cmd using administrator mode. Not sure how this can be an issue for so long in an install script. Sounds like they probably need to make the installer run in admin mode and make sure postInstall.bat is run. Note, the program is still slow to start, so I still saw the spinner for about 10 seconds before I was able to use it.

**Comment by babytee** [comment]
After i install run the postinstall.bat file it wosks for me but i not loading in the browser after creating an app

**Comment by kozfelipe** [comment]
Is nodejs or npm required to Desktop App works on Windows? Theres no docs or guides on that nearby the download page

**Comment by rmatzinger** [comment]
Installed nodejs and phonegap desktop (0.4.5) as administrator on Windows 10.  User is an administrator. First launch of phonegap got past the spinner but then froze without creating the web server.  Had to kill process because nothing was clickable, couldn't even move the app window on the screen. Second launch froze during startup with spinner stopped.   This app is unusable. 

![image](https://user-images.githubusercontent.com/37637828/62391981-12765480-b51b-11e9-83f6-a5e05fdbade0.png)

**Comment by adeyinkaroyal** [comment]
Hello All,

I'm using phonegap desktop (0.4.5) and it's working fine on my pc,
I have npm v. 5.6.0 installed and node v.8.11.4
Also, check to ensure that you have cordova installed on your pc via cmd prompt: cordova -v
I have cordova 9.0.0 (cordova-lib@9.0.1) installed and everything works perfectly.
The only challenge I once had was when creating a new project and was able to resolve this by ensuring that during creation of new project, my computer is connected to the internet. Without that, everything works perfectly.

Also, sometimes ago, I noticed that some versions of Phonegap wasn't working. I had to dig into my archive to get this. Should anyone desire to have it please reply below or send me your request to: adeyinkaroyal at outlook.com

![PhoneGap screeshot](https://user-images.githubusercontent.com/33792423/62392969-c817c680-b560-11e9-8aa3-2899181259e4.png)

**Comment by rmatzinger** [comment]
I guess somebody uses it.  Good for you.  However, I just uninstalled PhoneGap because my experience is that it is junk.  I followed the instructions on this page: https://phonegap.com/getstarted/  which makes no mention of Cordova or installing it.  The "complete" install docs here:  http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/ 
also neglect to mention npm, cordova, nodejs, etc. How is anyone supposed to know they are required?  After a huge waste of time searching for answers and trying what was suggested, I was never able to get it to run.   Now I've discovered that Apache took it over and named it Cordova,  according to WikiPedia:  https://en.wikipedia.org/wiki/Apache_Cordova     Apparently Apache has the latest version:  https://cordova.apache.org/  Why use PhoneGap when it clearly hasn't been maintained or updated since 2017.  I should have known better when I saw PhoneGap is an Adobe product.  I stopped using other Adobe products years ago.

**Comment by kingzley** [comment]
> I guess somebody uses it. Good for you. However, I just uninstalled PhoneGap because my experience is that it is junk. I followed the instructions on this page: https://phonegap.com/getstarted/ which makes no mention of Cordova or installing it. The "complete" install docs here: http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/
> also neglect to mention npm, cordova, nodejs, etc. How is anyone supposed to know they are required? After a huge waste of time searching for answers and trying what was suggested, I was never able to get it to run. Now I've discovered that Apache took it over and named it Cordova, according to WikiPedia: https://en.wikipedia.org/wiki/Apache_Cordova Apparently Apache has the latest version: https://cordova.apache.org/ Why use PhoneGap when it clearly hasn't been maintained or updated since 2017. I should have known better when I saw PhoneGap is an Adobe product. I stopped using other Adobe products years ago.

Thank you very much.
I am using Apache Cordova instead for development on my pc.
But would likely use Phonegap Build online for seamless cross platform deployment.

**Comment by fleduc** [comment]
**I HAVE SWITCH TO CORDOVA!**

I have copied my www folder into a newly created application and it worked on the first shot!
All this within 30 minutes of reading, install and configuration.

That's something that I never experienced while using Phonegap.  That's pretty sad because I have spent few weeks on training and trying to make Phonegap to work but at the end, it was a pretty frustrating experience...

[Cordova - Overview](https://cordova.apache.org/docs/en/latest/guide/overview/index.html)
[Cordova - My first app.](https://cordova.apache.org/docs/en/latest/guide/cli/index.html)

**Comment by zaidmo123** [comment]
Same issue with a brand new install in March 2020 of Phonegap Desktop 0.45 on Windows 10 64-bit.
With 6.13.7, which was upgraded to 6.14.3
Node js vesion v13.11.0

The app is stuck on the loading screen.
I have tried:
1. Adding Phonegap to bypass Windows Defender firewall
2. Deleted the Appdata/Roaming/Phonegap cache
3. Run the app in administrator mode

**Comment by adeyinkaroyal** [comment]
![phone-gap-shots](https://user-images.githubusercontent.com/33792423/77231665-c573eb00-6b9c-11ea-894d-a3694047f97f.png)

Since several users are still having issue setting up PhoneGap, I've choose to share my with you all.
As you can see in the screenshot above, it's still working as at Mar.21,2020 and I hope it works on your PC too.
This version does not require installation. You unzip it to any location of your choice and run the phonegap from there. 
I've shared it via my onedrive account, kindly download it from there and use. Link is: 
https://1drv.ms/u/s!AlfeCLUWjs1UvGDLmykF4DMSwB4y?e=gngxPs

![others](https://user-images.githubusercontent.com/33792423/77231832-a7f35100-6b9d-11ea-8593-236af21d39a2.png)

Also, other resources on my PC are:
node -v 8.11.4
cordova -v 9.0.0
phonegap -v 8.2.2

I hope this works for you.
---Helping Humanity

**Comment by zaidmo123** [comment]
Thanks @adeyinkaroyal  
I managed to launch your version

**Comment by Shadowofdeath99** [comment]
hello its not working  u must download this file win64 not win 32 v   
https://github.com/phonegap/phonegap-app-desktop/releases/download/0.1.7/PhoneGapSetup-win64.exe  thanks

**Comment by EddiesTech** [comment]
> hello its not working u must download this file win64 not win 32 v
> https://github.com/phonegap/phonegap-app-desktop/releases/download/0.1.7/PhoneGapSetup-win64.exe thanks

@Shadowofdeath99 Thanks, this worked :)

**Comment by adeyinkaroyal** [comment]
> 
> 
> hello its not working u must download this file win64 not win 32 v
> https://github.com/phonegap/phonegap-app-desktop/releases/download/0.1.7/PhoneGapSetup-win64.exe thanks

@Shadowofdeath99 Thanks for the update. good to have both then x86 and x64 version.

**Comment by passariello** [comment]
> 
> 
> ![phone-gap-shots](https://user-images.githubusercontent.com/33792423/77231665-c573eb00-6b9c-11ea-894d-a3694047f97f.png)
> 
> Since several users are still having issue setting up PhoneGap, I've choose to share my with you all.
> As you can see in the screenshot above, it's still working as at Mar.21,2020 and I hope it works on your PC too.
> This version does not require installation. You unzip it to any location of your choice and run the phonegap from there.
> I've shared it via my onedrive account, kindly download it from there and use. Link is:
> https://1drv.ms/u/s!AlfeCLUWjs1UvGDLmykF4DMSwB4y?e=gngxPs
> 
> ![others](https://user-images.githubusercontent.com/33792423/77231832-a7f35100-6b9d-11ea-8593-236af21d39a2.png)
> 
> Also, other resources on my PC are:
> node -v 8.11.4
> cordova -v 9.0.0
> phonegap -v 8.2.2
> 
> I hope this works for you.
> ---Helping Humanity

This work for me... The official install it's completely frozen :(
Windows 10 / avast AV

**Comment by howardkhl** [comment]
> hello its not working u must download this file win64 not win 32 v
> https://github.com/phonegap/phonegap-app-desktop/releases/download/0.1.7/PhoneGapSetup-win64.exe thanks

64bit solved the issue for me. Thanks!

**Comment by justingolden21** [comment]
![image](https://user-images.githubusercontent.com/30274440/79407813-c48d6980-7f4e-11ea-9cbb-275e158ea1f3.png)

On [StackOverflow](https://stackoverflow.com/questions/36775178/phonegap-desktop-not-launching-properly-keeps-loading) they said it was fixed in 0.3.1, however I keep encountering if after relaunching, reinstalling, and restarting my PC.

**Comment by ikbal-nayem** [comment]
[This](https://github.com/phonegap/phonegap-app-desktop/issues/739#issuecomment-602072722) worked for me. 
Thank you so much @adeyinkaroyal

**Comment by ikbal-nayem** [comment]
> ![phone-gap-shots](https://user-images.githubusercontent.com/33792423/77231665-c573eb00-6b9c-11ea-894d-a3694047f97f.png)
> 
> Since several users are still having issue setting up PhoneGap, I've choose to share my with you all.
> As you can see in the screenshot above, it's still working as at Mar.21,2020 and I hope it works on your PC too.
> This version does not require installation. You unzip it to any location of your choice and run the phonegap from there.
> I've shared it via my onedrive account, kindly download it from there and use. Link is:
> https://1drv.ms/u/s!AlfeCLUWjs1UvGDLmykF4DMSwB4y?e=gngxPs
> 
> ![others](https://user-images.githubusercontent.com/33792423/77231832-a7f35100-6b9d-11ea-8593-236af21d39a2.png)
> 
> Also, other resources on my PC are:
> node -v 8.11.4
> cordova -v 9.0.0
> phonegap -v 8.2.2
> 
> I hope this works for you.
> ---Helping Humanity

This worked for me.
**Thank you so match** @adeyinkaroyal

**Comment by gitUserDiegoS** [comment]
> This worked for me.
> **Thank you so match** @adeyinkaroyal

and for me, with:
node -v
v10.15.3

cordova -v
9.0.0 (cordova-lib@9.0.1)

Thanks

**Comment by Reynardt** [comment]
> > ![phone-gap-shots](https://user-images.githubusercontent.com/33792423/77231665-c573eb00-6b9c-11ea-894d-a3694047f97f.png)
> > Since several users are still having issue setting up PhoneGap, I've choose to share my with you all.
> > As you can see in the screenshot above, it's still working as at Mar.21,2020 and I hope it works on your PC too.
> > This version does not require installation. You unzip it to any location of your choice and run the phonegap from there.
> > I've shared it via my onedrive account, kindly download it from there and use. Link is:
> > https://1drv.ms/u/s!AlfeCLUWjs1UvGDLmykF4DMSwB4y?e=gngxPs
> > ![others](https://user-images.githubusercontent.com/33792423/77231832-a7f35100-6b9d-11ea-8593-236af21d39a2.png)
> > Also, other resources on my PC are:
> > node -v 8.11.4
> > cordova -v 9.0.0
> > phonegap -v 8.2.2
> > I hope this works for you.
> > ---Helping Humanity
> 
> This worked for me.
> **Thank you so match** @adeyinkaroyal

You're a legend thanks!

**Comment by hmnt-zy** [comment]
> hello its not working u must download this file win64 not win 32 v
> https://github.com/phonegap/phonegap-app-desktop/releases/download/0.1.7/PhoneGapSetup-win64.exe thanks

thanks it worked

**Comment by DebalB** [comment]
> 
> 
> ![phone-gap-shots](https://user-images.githubusercontent.com/33792423/77231665-c573eb00-6b9c-11ea-894d-a3694047f97f.png)
> 
> Since several users are still having issue setting up PhoneGap, I've choose to share my with you all.
> As you can see in the screenshot above, it's still working as at Mar.21,2020 and I hope it works on your PC too.
> This version does not require installation. You unzip it to any location of your choice and run the phonegap from there.
> I've shared it via my onedrive account, kindly download it from there and use. Link is:
> https://1drv.ms/u/s!AlfeCLUWjs1UvGDLmykF4DMSwB4y?e=gngxPs
> 
> ![others](https://user-images.githubusercontent.com/33792423/77231832-a7f35100-6b9d-11ea-8593-236af21d39a2.png)
> 
> Also, other resources on my PC are:
> node -v 8.11.4
> cordova -v 9.0.0
> phonegap -v 8.2.2
> 
> I hope this works for you.
> ---Helping Humanity

thanks a lot @adeyinkaroyal.
your version is working fine for me.
I am using following versions:
node -v v14.4.0
cordova not installed
phonegap -v 9.0.0
I wonder whats the difference between your and the official version which was not working.
I also tried the 64-bit version shared by @Shadowofdeath99 
https://github.com/phonegap/phonegap-app-desktop/releases/download/0.1.7/PhoneGapSetup-win64.exe
It launched correctly but did not display the PhoneGap image correctly. So I guess will continue with the 32bit working version as of now.
I was also able to connect the desktop App with the PhoneGap Android App using your version.

**Comment by KCole313** [comment]
> > ![phone-gap-shots](https://user-images.githubusercontent.com/33792423/77231665-c573eb00-6b9c-11ea-894d-a3694047f97f.png)
> > Since several users are still having issue setting up PhoneGap, I've choose to share my with you all.
> > As you can see in the screenshot above, it's still working as at Mar.21,2020 and I hope it works on your PC too.
> > This version does not require installation. You unzip it to any location of your choice and run the phonegap from there.
> > I've shared it via my onedrive account, kindly download it from there and use. Link is:
> > https://1drv.ms/u/s!AlfeCLUWjs1UvGDLmykF4DMSwB4y?e=gngxPs
> > ![others](https://user-images.githubusercontent.com/33792423/77231832-a7f35100-6b9d-11ea-8593-236af21d39a2.png)
> > Also, other resources on my PC are:
> > node -v 8.11.4
> > cordova -v 9.0.0
> > phonegap -v 8.2.2
> > I hope this works for you.
> > ---Helping Humanity
> 
> thanks a lot @adeyinkaroyal.
> your version is working fine for me.
> I am using following versions:
> node -v v14.4.0
> cordova not installed
> phonegap -v 9.0.0
> I wonder whats the difference between your and the official version which was not working.
> I also tried the 64-bit version shared by @Shadowofdeath99
> https://github.com/phonegap/phonegap-app-desktop/releases/download/0.1.7/PhoneGapSetup-win64.exe
> It launched correctly but did not display the PhoneGap image correctly. So I guess will continue with the 32bit working version as of now.
> I was also able to connect the desktop App with the PhoneGap Android App using your version.

The difference between the official version and the version @adeyinkaroyal provided is that theirs includes the phonegap module and all it's dependencies in the resources\app.asar.unpacked\node_modules directory which the postinstall.bat script is supposed to be taking care of in the official version. However it seems there is an issue with older versions of npm (https://github.com/npm/cli/issues/681) which is causing the the postinstall.bat script to hit an error when it tries to install the phonegap module.

![image](https://user-images.githubusercontent.com/5840343/84095994-9c057700-a9b5-11ea-91b9-338d4b9d401a.png)

**Comment by DebalB** [comment]
> 
> 
> > > ![phone-gap-shots](https://user-images.githubusercontent.com/33792423/77231665-c573eb00-6b9c-11ea-894d-a3694047f97f.png)
> > > Since several users are still having issue setting up PhoneGap, I've choose to share my with you all.
> > > As you can see in the screenshot above, it's still working as at Mar.21,2020 and I hope it works on your PC too.
> > > This version does not require installation. You unzip it to any location of your choice and run the phonegap from there.
> > > I've shared it via my onedrive account, kindly download it from there and use. Link is:
> > > https://1drv.ms/u/s!AlfeCLUWjs1UvGDLmykF4DMSwB4y?e=gngxPs
> > > ![others](https://user-images.githubusercontent.com/33792423/77231832-a7f35100-6b9d-11ea-8593-236af21d39a2.png)
> > > Also, other resources on my PC are:
> > > node -v 8.11.4
> > > cordova -v 9.0.0
> > > phonegap -v 8.2.2
> > > I hope this works for you.
> > > ---Helping Humanity
> > 
> > 
> > thanks a lot @adeyinkaroyal.
> > your version is working fine for me.
> > I am using following versions:
> > node -v v14.4.0
> > cordova not installed
> > phonegap -v 9.0.0
> > I wonder whats the difference between your and the official version which was not working.
> > I also tried the 64-bit version shared by @Shadowofdeath99
> > https://github.com/phonegap/phonegap-app-desktop/releases/download/0.1.7/PhoneGapSetup-win64.exe
> > It launched correctly but did not display the PhoneGap image correctly. So I guess will continue with the 32bit working version as of now.
> > I was also able to connect the desktop App with the PhoneGap Android App using your version.
> 
> The difference between the official version and the version @adeyinkaroyal provided is that theirs includes the phonegap module and all it's dependencies in the resources\app.asar.unpacked\node_modules directory which the postinstall.bat script is supposed to be taking care of in the official version. However it seems there is an issue with older versions of npm ([npm/cli#681](https://github.com/npm/cli/issues/681)) which is causing the the postinstall.bat script to hit an error when it tries to install the phonegap module.
> 
> ![image](https://user-images.githubusercontent.com/5840343/84095994-9c057700-a9b5-11ea-91b9-338d4b9d401a.png)

Thanks for clarifying @KCole313 , I get the same error with the postinstall.bat script. Glad to have a working version anyways.

**Comment by DaniloRJBR** [comment]
4 Anos depois e o problema não foi resolvido... Mesmo problema aqui.

**Comment by JTorresConsulta** [comment]
Thank you DebalB  !!! This compilation works on Windows 10 
https://1drv.ms/u/s!AlfeCLUWjs1UvGDLmykF4DMSwB4y?e=gngxPs
