### ISSUE TITLE
Project Create Failed with code 1

### ISSUE THREAD

**Issue by karlco1990** [phonegap/phonegap-app-desktop#750]
### PhoneGap Desktop version
Newest
### Computer OS version
Mac OS EL Capitan

### Network Type (home/corporate)
Home

### Is your network using a proxy?
No
### Computer / Network security (firewall / anti-virus / disk encryption)
No
### Are you using VMs on your computer?
NO
### Do you have multiple network adapters (or virtual network adapters)?
NO
### Are you using VPN?
NO
### Expected Behaviour
To pass to the next screen and let me begin. 
### Actual Behaviour
Error Message Project Create Failed with code 1
#### Error messages
Project Create Failed with code 1

**Comment by emadz** [comment]
I have same issue with MacOS v10.12 Sierra

**Comment by surajpindoria** [comment]
Hey @karlco1990 & @emadz,

I am able to recreate this issue and will take a look into this. Thanks for reporting it.

**Comment by delahere** [comment]
I have the same problem as well on my Mac, Sierra 10.12.1. A colleague much more experience with Mac than I was able to reproduce it on his Mac as well.

**Comment by hermwong** [comment]
On OSX, we've found that we can build the release version of 0.4.2 locally and have it create project properly, however once we compress (create the `.zip`) for release and then unzip the `.zip` file we can successfully reproduce this issue.

I'm going to try the above use case on Windows to see if we get the same result.

**Comment by hermwong** [comment]
Tested the use case on Windows 10 VM.

I was able to create a project successfully with a local release build of 0.4.2 and also successfully able to create a project when I zipped & then unzipped 0.4.2 on my Windows 10 VM.

**Comment by AIMMOTH** [comment]
Windows 10, installed PhoneGap 0.4.2, starting with "Server is offline", created new blank project and get "Project create failed with code 1"

**Comment by c0mm0n** [comment]
Confirmed working with local release build on the same computer the downloaded binary failed.

**Comment by hermwong** [comment]
@AIMMOTH so you had Node installed on your Windows computer before installing PhoneGap Desktop?

**Comment by mccumb01** [comment]
Same issue, Mac El Capitan, PhoneGap v0.4.2. Creating initial "Hello World" app fails with Error Code 1. After that, trying to set a different file path pops up the red warning box saying the directory "does not contain config.xml", which was issue #331 reported in Mar 2015.

**Comment by kerrishotts** [comment]
I can replicate the issue on my Mac as well with 0.4.2.

macOS 10.11.6
Node is installed (via nvm)

**Comment by FFK-EDV** [comment]
I just downloaded the 0.4.2 on a fresh and clean Windows install. Creation of a project (Hello World) ended up in the already mentioned error message.

AIMMOTH had the right solution for this.
I did the same as he did:
Installing node.js by myself and then reinstalling PhoneGap. Now it's working fine.

Seems like there is something still wrong in the installer for nodeJS coming with PhoneGap.

**Comment by theophilbethel** [comment]
Same issue today on Windows 10 with 0.4.2 creating a blank project (same with other templates)

**Comment by juanmoncada** [comment]
Same issue. macOS Sierra Verion 10.12.2 (16C67). Nodejs was already installed.

Deleted 0.4.2. Installed and created project with 0.4.1. Deleted 0.4.1 and reinstalled 0.4.2 to continue with project. Seems to work for now. Very inconvenient obviously, but works for me.

**Comment by sandip-stats** [comment]
Same issue. 

Version Details
1. macOS Sierra (V 10.12.1). 
2. PhoneGap (v0.4.2)
3. Node Version (v4.4.5)

Any idea as to when will this be fixed?

**Comment by surajpindoria** [comment]
Hi @sandip-stats,

We are aware of the issue and are currently working on it. In the meantime you can try using version 0.4.1 until we are able to release a new one.

**Comment by samuraii** [comment]
Please advice how to download later version

**Comment by juanmoncada** [comment]
@samuraii try https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.4.1

**Comment by kranthi-paidi** [comment]
Hi @surajpindoria 

Any update on when can we expect a fix for this?

Thanks,
Kranthi

**Comment by hermwong** [comment]
We're currently testing out a fix for this issue and should have the patch released in early January.

**Comment by andythedandyone** [comment]
if it has a bug now and it was working before, why dont just roll back to previous working version until this bug is addressed?

**Comment by hermwong** [comment]
We're recommending that users rollback to [0.4.1](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.4.1). We've disabled the update prompt so that it shouldn't ask users to update to 0.4.2.

**Comment by hermwong** [comment]
wil be fixed in release 0.4.3 see issue #752

**Comment by surajpindoria** [comment]
We have released an updated version, [0.4.3](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.4.3) that should resolve this issue.

**Comment by sonstiges** [comment]
Doesn´t work for me. Uninstalled Node and Phonegap 4.2. 
Cleaned registry and deleted all files and dir left.
Tried it again with revo uninstaller
no chance. Error still there.

Windows 10 64 Bit

**Comment by hermwong** [comment]
@sonstiges try using the newest version [0.4.3](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.4.3)

**Comment by andythedandyone** [comment]
The problem is that a lot people just don't take their time to read. It is hard to not post this comment when the very last post was clearly stating the problem has been solved with version 0.4.3. Why in the world would you persist in a failed deprecated version? Please try version 0.4.3, it has fixed the previous version issues.

**Comment by sonstiges** [comment]
Sorry, my text wasn´t written very well. I tried with 4.3. The error is still there. Even on my new Surface Book 4 I installed 0.4.3 for the first time. I read the manual and looked for solutions for nearly 4 hours. Error is still there when you use an ID. I tried a Mac Book, Surface 4 and Win 10 and Win7 (32 Bit & 64 Bit).

**Comment by andythedandyone** [comment]
Let me know what exactly error you are getting and I will try to help, I
can assure that on El Capitan it works.

**Comment by sskelly** [comment]
I still receive this error with 0.4.3 installed using the windows exe installer. I do already have node on my computer so I am not sure if this is somehow conflicting?

**Comment by rehanvdm** [comment]
Same problem as sskelly:

> I still receive this error with 0.4.3 installed using the windows exe installer. I do already have node on my computer so I am not sure if this is somehow conflicting?

**Comment by rehanvdm** [comment]
Problem solved. Make sure you have the latest Nodejs installed. I was using the old one to do work on AWS Lambda

**Comment by sskelly** [comment]
Fixed. Apparently my Bitdefender Ransomware module was blocking something in the background.

**Comment by sseowhui** [comment]
Hi there,

I am having the same problem: "Project Create Failed with Code 1".
Installed the following packages on my iMac (macOS Sierra v 10.12.1):

PhoneGap (v0.4.3)
Node (v7.4.0)

I have been struggling with these for some time. 
Please ADVICE.

Thanks.

**Comment by acidjazz** [comment]
@hermwong 100% not fixed and duplicatable no matter what i choose creating a project. definitely not able to even create a project at all anymore

**Comment by hermwong** [comment]
@acidjazz,

Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?
11. Steps to that you used to reproduce the issue.

**Comment by acidjazz** [comment]
absolutely

1. latest, 0.4.3
2. only installed the desktop version
3. haven't gotten that far
5. internet sonic.net DSL, no proxy, no firewall/etc, no VM's, 1 adapter, no VPN

macOS Sierra 10.12.3
node v7.1.0
phonegap v0.4.3

![image](https://cloud.githubusercontent.com/assets/967369/23869369/f6c7ad50-07df-11e7-8da2-8989113d6d27.png)

![image](https://cloud.githubusercontent.com/assets/967369/23869381/fd80ec6a-07df-11e7-9452-413f0c0b0519.png)

**Comment by GaryMcD** [comment]
I had the same dialog: "Project create failed with code 1".

This only occurred when the ID's second string started with an integer.
Example of failure: "com.19.example"
Example of working: "com.a19.example"

**Comment by surajpindoria** [comment]
Hi @GaryMcD,

This is the expected behavior. When dealing with the IDs, we have to adhere to the rules set by each platform (android, iOS, windows), android being the most restrictive. Therefore all IDs must be set to use all of these restrictions.

**Comment by acidjazz** [comment]
@andythedandyone @hermwong still think its fixed in 0..4.3 ? I suggest you re-open this.  @surajpindoria maybe a proper error message might be the solution?

**Comment by surajpindoria** [comment]
@acidjazz it's on my todo list, already filed an issue for input validation

**Comment by ricardomasao** [comment]
I dealt with the same problem both in version 0.4.3 and 0.4.1.

Node Version 7.5.0

Any solution?

**Comment by humanrider** [comment]
I to am having the same problem when creating a project. I tried uninstalling and installing all GIT, Node.js and Phonegap Desktop multiple times and still have the same problem appearing.

**Comment by chasebank** [comment]
Just encountered this. Brand new install of Phonegap Desktop, Windows 10.

@surajpindoria 's post about integers in the ID tipped me off to look there. I was getting the error with "com.phonegap-project". I tried removing the dash and just using "com.phonegapproject" and it worked without issue.

**Comment by acidjazz** [comment]
@andythedandyone still want to keep this closed?

**Comment by dirtyspark23** [comment]
PhoneGap is not designed to be used on Windows 10, troubleshoot compatibility and set the option to Windows 8 and this should solve your issue.
