### ISSUE TITLE
Phonegap project doesn't get updated on Platforms/Browser on file change

### ISSUE THREAD

**Issue by Valkhan** [phonegap/phonegap-app-desktop#886]
## _System Configuration_
Core i3 3.3ghz
6gb RAM

### PhoneGap Desktop version
v0.4.5

### Computer OS version
Windows 10 64bits

### Network Type (home/corporate)
Home

### Is your network using a proxy?
No

### Computer / Network security (firewall / anti-virus / disk encryption)
No

### Are you using VMs on your computer?
Yes

### Do you have multiple network adapters (or virtual network adapters)?
Yes, but only the phisical device is enabled, all VM network adapters are disabled.

### Are you using VPN?
No

### Expected Behaviour
Update a HTML, CSS, JS file in <project>/www/* and the file gets updated on <project>/platforms/browser/*

### Actual Behaviour
Files are not updated on platforms/browser/* meaning that the old versions are shown when testing in browser.

### Steps to Reproduce 
Serve a project.
Update any file.
Test on browser.

#### Error messages
Not applicable.

### Example:

I've a project called myapp in c:/xampp/htdocs/myapp

In my app.js I have:
`
prompt('Hello World!');
`

When I serve this project and run it in browser, Phonegap will copy my /www/* files to /platforms/browser/* and a prompt message will show.

Now i've changed the file to:
`
alert('Hello World!');
`

When I serve this project and run it in browser, Phonegap SHOULD copy my /www/* files to /platforms/browser/* and an alert message SHOULD appear, but instead it keeps the old file and a prompt message is shown.

NOTE: I've tried all the following:

- clearing cache [I'm running Google Chrome (Version 67.0.3396.87 64 bits) with dev console active and disabled cache]
- rebooting system
- deleting all plugins
- deleting platforms folders
- recreating the project
- running Phonegap as admin

ALSO, Phonegap HAS detected that the file (app.js) has changed and reloaded the page, but it does not replicate the file to platforms.

This is the log when I start serving the project:

```
starting app server...
listening on 10.10.2.210:3000
200 /
200 /socket.io/socket.io.js
200 /lib/framework7/css/framework7.keypad.min.css
200 /lib/font-awesome-4.7.0/css/font-awesome.min.css
200 /css/styles.min.css
200 /lib/framework7/css/framework7.material.min.css
200 /lib/framework7/css/framework7.material.colors.min.css
200 /cordova.js
200 /js/funcoes.min.js
200 /js/combined.js
200 /socket.io/?EIO=3&transport=polling&t=MGN_B6P
200 /js/classes.min.js
404 /img/logo.gif
200 /js/app.min.js
200 /socket.io/?EIO=3&transport=polling&t=MGN_B7C&sid=pTFgKisXvusFhsV-AAAF
200 /socket.io/?EIO=3&transport=polling&t=MGN_B7b&sid=pTFgKisXvusFhsV-AAAF
200 /lib/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0
200 /socket.io/?EIO=3&transport=polling&t=MGN_BA4
404 /js/framework7.min.js.map
200 /cordova_plugins.js
200 /socket.io/?EIO=3&transport=polling&t=MGN_BBi&sid=HCiCKosOQE3MaYpcAAAG
200 /plugins/cordova-plugin-camera/www/CameraConstants.js
200 /plugins/cordova-plugin-camera/www/CameraPopoverOptions.js
200 /plugins/cordova-plugin-camera/www/Camera.js
200 /plugins/cordova-plugin-camera/src/browser/CameraProxy.js
200 /plugins/cordova-plugin-device/www/device.js
200 /plugins/cordova-plugin-device/src/browser/DeviceProxy.js
200 /plugins/cordova-plugin-file/www/DirectoryEntry.js
200 /plugins/cordova-plugin-file/www/DirectoryReader.js
200 /plugins/cordova-plugin-file/www/Entry.js
200 /plugins/cordova-plugin-file/www/File.js
200 /plugins/cordova-plugin-file/www/FileEntry.js
200 /plugins/cordova-plugin-file/www/FileError.js
200 /socket.io/?EIO=3&transport=polling&t=MGN_BCx&sid=HCiCKosOQE3MaYpcAAAG
200 /plugins/cordova-plugin-file/www/FileSystem.js
200 /plugins/cordova-plugin-file/www/FileUploadOptions.js
200 /plugins/cordova-plugin-file/www/FileReader.js
200 /plugins/cordova-plugin-file/www/FileUploadResult.js
200 /plugins/cordova-plugin-file/www/FileWriter.js
200 /plugins/cordova-plugin-file/www/Flags.js
200 /plugins/cordova-plugin-file/www/LocalFileSystem.js
200 /plugins/cordova-plugin-file/www/Metadata.js
200 /plugins/cordova-plugin-file/www/ProgressEvent.js
200 /plugins/cordova-plugin-file/www/fileSystems.js
200 /plugins/cordova-plugin-file/www/requestFileSystem.js
200 /plugins/cordova-plugin-file/www/browser/isChrome.js
200 /plugins/cordova-plugin-file/www/resolveLocalFileSystemURI.js
200 /plugins/cordova-plugin-file/www/browser/Preparing.js
200 /plugins/cordova-plugin-file/www/fileSystemPaths.js
200 /plugins/cordova-plugin-file/src/browser/FileProxy.js
200 /plugins/cordova-plugin-file/www/browser/FileSystem.js
200 /plugins/cordova-plugin-file-transfer/www/FileTransferError.js
200 /plugins/cordova-plugin-file-transfer/www/FileTransfer.js
200 /plugins/cordova-plugin-file-transfer/www/browser/FileTransfer.js
200 /plugins/cordova-plugin-inappbrowser/www/inappbrowser.js
200 /socket.io/?EIO=3&transport=polling&t=MGN_BEw&sid=HCiCKosOQE3MaYpcAAAG
200 /plugins/cordova-plugin-inappbrowser/src/browser/InAppBrowserProxy.js
200 /plugins/cordova-plugin-network-information/www/network.js
200 /plugins/cordova-plugin-network-information/www/Connection.js
200 /plugins/cordova-plugin-network-information/src/browser/network.js
200 /plugins/cordova-plugin-statusbar/www/statusbar.js
200 /plugins/phonegap-plugin-barcodescanner/src/browser/BarcodeScannerProxy.js
200 /plugins/phonegap-plugin-barcodescanner/www/barcodescanner.js
 adding proxy for Camera
200 /socket.io/?EIO=3&transport=polling&t=MGN_BGz&sid=HCiCKosOQE3MaYpcAAAG
 adding proxy for Device
 adding proxy for File
 adding proxy for InAppBrowser
 adding proxy for NetworkStatus
 Error: exec proxy not found for :: StatusBar :: _ready
 adding proxy for BarcodeScanner
200 /socket.io/?EIO=3&transport=polling&t=MGN_BHM&sid=HCiCKosOQE3MaYpcAAAG
200 /socket.io/?EIO=3&transport=polling&t=MGN_BGS&sid=HCiCKosOQE3MaYpcAAAG
 Persistent fs quota granted
200 /socket.io/?EIO=3&transport=polling&t=MGN_BHi&sid=HCiCKosOQE3MaYpcAAAG
200 /socket.io/?EIO=3&transport=polling&t=MGN_BHn&sid=HCiCKosOQE3MaYpcAAAG
200 /socket.io/?EIO=3&transport=polling&t=MGN_BJD&sid=HCiCKosOQE3MaYpcAAAG
200 /socket.io/?EIO=3&transport=polling&t=MGN_BKp&sid=HCiCKosOQE3MaYpcAAAG
200 /socket.io/?EIO=3&transport=polling&t=MGN_BMM&sid=HCiCKosOQE3MaYpcAAAG
200 /socket.io/?EIO=3&transport=polling&t=MGN_BNx&sid=HCiCKosOQE3MaYpcAAAG
 adding proxy for Camera
 adding proxy for Device
 adding proxy for File
 adding proxy for InAppBrowser
 adding proxy for NetworkStatus
 Error: exec proxy not found for :: StatusBar :: _ready
 adding proxy for BarcodeScanner
 Persistent fs quota granted
200 /socket.io/?EIO=3&transport=polling&t=MGN_BPX&sid=HCiCKosOQE3MaYpcAAAG
```

This is the Log when I've changed the 'index.html' file:

```
file changed <PATHTOPROJECT>\www\index.html
200 /
200 /lib/framework7/css/framework7.keypad.min.css
404 /img/logo.gif
200 /lib/font-awesome-4.7.0/css/font-awesome.min.css
200 /css/styles.min.css
200 /lib/framework7/css/framework7.material.min.css
200 /cordova.js
200 /lib/framework7/css/framework7.material.colors.min.css
200 /socket.io/socket.io.js
200 /js/funcoes.min.js
200 /js/classes.min.js
200 /js/app.min.js
200 /js/combined.js
200 /lib/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0
200 /cordova_plugins.js
200 /plugins/cordova-plugin-camera/www/CameraConstants.js
200 /plugins/cordova-plugin-camera/www/Camera.js
200 /plugins/cordova-plugin-camera/src/browser/CameraProxy.js
200 /plugins/cordova-plugin-device/www/device.js
200 /plugins/cordova-plugin-device/src/browser/DeviceProxy.js
200 /plugins/cordova-plugin-camera/www/CameraPopoverOptions.js
200 /plugins/cordova-plugin-file/www/DirectoryEntry.js
200 /plugins/cordova-plugin-file/www/DirectoryReader.js
200 /plugins/cordova-plugin-file/www/Entry.js
200 /plugins/cordova-plugin-file/www/File.js
200 /plugins/cordova-plugin-file/www/FileEntry.js
200 /plugins/cordova-plugin-file/www/FileError.js
200 /plugins/cordova-plugin-file/www/FileReader.js
200 /plugins/cordova-plugin-file/www/FileSystem.js
200 /plugins/cordova-plugin-file/www/FileUploadOptions.js
200 /plugins/cordova-plugin-file/www/FileUploadResult.js
200 /plugins/cordova-plugin-file/www/Flags.js
200 /plugins/cordova-plugin-file/www/FileWriter.js
200 /plugins/cordova-plugin-file/www/LocalFileSystem.js
200 /plugins/cordova-plugin-file/www/Metadata.js
200 /plugins/cordova-plugin-file/www/ProgressEvent.js
200 /plugins/cordova-plugin-file/www/fileSystems.js
200 /plugins/cordova-plugin-file/www/requestFileSystem.js
200 /plugins/cordova-plugin-file/www/resolveLocalFileSystemURI.js
200 /plugins/cordova-plugin-file/www/browser/isChrome.js
200 /plugins/cordova-plugin-file/www/browser/Preparing.js
200 /plugins/cordova-plugin-file/www/fileSystemPaths.js
200 /plugins/cordova-plugin-file/www/browser/FileSystem.js
200 /plugins/cordova-plugin-file-transfer/www/FileTransferError.js
200 /plugins/cordova-plugin-file-transfer/www/FileTransfer.js
200 /plugins/cordova-plugin-file/src/browser/FileProxy.js
200 /plugins/cordova-plugin-file-transfer/www/browser/FileTransfer.js
200 /plugins/cordova-plugin-inappbrowser/www/inappbrowser.js
200 /plugins/cordova-plugin-network-information/www/network.js
200 /plugins/cordova-plugin-inappbrowser/src/browser/InAppBrowserProxy.js
200 /plugins/cordova-plugin-network-information/www/Connection.js
200 /plugins/cordova-plugin-network-information/src/browser/network.js
200 /plugins/cordova-plugin-statusbar/www/statusbar.js
200 /plugins/phonegap-plugin-barcodescanner/www/barcodescanner.js
200 /plugins/phonegap-plugin-barcodescanner/src/browser/BarcodeScannerProxy.js
200 /socket.io/?EIO=3&transport=polling&t=MGN-Ek7
404 /js/framework7.min.js.map
200 /socket.io/?EIO=3&transport=polling&t=MGN-Eld&sid=aYPxu5nV_EscEmg5AAAE
 adding proxy for Camera
200 /socket.io/?EIO=3&transport=polling&t=MGN-En8&sid=aYPxu5nV_EscEmg5AAAE
 adding proxy for Device
 adding proxy for File
 adding proxy for InAppBrowser
 adding proxy for NetworkStatus
 Error: exec proxy not found for :: StatusBar :: _ready
 adding proxy for BarcodeScanner
 Persistent fs quota granted
200 /socket.io/?EIO=3&transport=polling&t=MGN-EnX&sid=aYPxu5nV_EscEmg5AAAE
```

**Comment by Valkhan** [comment]
Sorry for the late response, I forgot to mention and close this issue (I was travelling), it turns out that I was using an obsolete plugin (cordova-custom-config) and it was messing with the download of plugins when I've deleted all files causing the crash.

@benhalhead please check if you're having the same issue.

**Comment by purplecabbage** [comment]
@benhalhead Are you still having this issue?

**Comment by NirBentzy** [comment]
+1

Is there any way to clear the cache manually?

**Comment by purplecabbage** [comment]
@NirBentzy are you using cordova-custom-config plugin? Does @Valkhan 's solution work for you?

**Comment by NirBentzy** [comment]
I have no such as plugin installed on my project.

**Comment by NirBentzy** [comment]
Any idea how to solve this?

**Comment by purplecabbage** [comment]
@nirbentzy please post a stacktrace similar to the initial reporter did. 
Since @valkhan ‘s issue was resolved I have to assume this is something different.

**Comment by Valkhan** [comment]
@NirBentzy I'll recomend deleting the plugins folder and restart the server, it will force the download of the  plugins again and if any of them fail to load, it's probably an incompatibility with that particular plugin.

**Comment by awilsondot** [comment]
I'm having this same issue, made code changes in the app and still getting behavior of the previous code. Ran phonegap rebuild browser and it didn't help.

Here is the stack trace
starting app server...
listening on 152.122.117.68:3000
200 /socket.io/?EIO=3&transport=polling&t=MZAM4W_
200 /socket.io/?EIO=3&transport=polling&t=MZAM4XB&sid=IKUrMTiA3CiEahi2AAAA
404 /
404 /
404 /
404 /
starting app server...
listening on 152.122.117.68:3000
starting app server...
listening on 152.122.117.68:3000
200 /
200 /css/highlightPlugin.css
200 /js/themeroller-birm.css
200 /css/index.css
200 /css/jquery.mmenu.all.css
200 /css/jquery.mobile.icons.min.css
200 /js/jquery.mobile-1.4.5.css
200 /css/pinchzoomer.min.css
304 /socket.io/socket.io.js
200 /css/jquery-impromptu.css
200 /css/jquery.mmenu.themes.css
200 /css/clean-blue.css
200 /css/glossary.css
200 /css/BIRM-Custom.css
200 /js/jquery-2.1.3.js
200 /js/jquery.highlight-5.js
200 /js/jstorage.js
200 /js/highlight/HighLight.js
200 /js/json2.js
200 /js/jquery.waitforimages.js
200 /js/jquery.mmenu.all.min.js
200 /js/jquery.mmenu.jquerymobile.min.js
200 /js/moment.js
200 /js/jquery.mousewheel.min.js
200 /js/jquery.mobile-1.4.5.js
200 /js/jquery.hammer.min.js
200 /js/modernizr.min.js
200 /js/jquery.pinchzoomer.min.js
200 /js/TweenMax.min.js
200 /js/fastclick.js
200 /js/jquery.unveil.js
200 /js/jquery.simplemodal.js
200 /js/jquery.fileDownload.js
200 /js/jquery.cycle2.js
200 /js/jquery.cycle2.center.js
200 /js/jquery.cycle2.swipe.js
200 /js/FileSystem.js
200 /js/jquery-impromptu.js
200 /js/BIRM.js
200 /js/Connection.js
200 /js/Download.js
200 /js/ImportExport.js
200 /js/rangy/rangy-selectionsaverestore.js
200 /js/rangy/rangy-classapplier.js
200 /socket.io/?EIO=3&transport=polling&t=MZAMQDK
200 /socket.io/?EIO=3&transport=polling&t=MZAMQVA&sid=cp85-VT8GiJ_dF8RAAAB
 BIRMApp.LoadChapters: Preloading BIRM EPUB chapters.
200 /socket.io/?EIO=3&transport=polling&t=MZAMQVH&sid=cp85-VT8GiJ_dF8RAAAB
200 /js/simple-expand.js
 BIRMApp.LoadVideos: Preloading BIRM videos.
200 /socket.io/?EIO=3&transport=polling&t=MZAMQVN&sid=cp85-VT8GiJ_dF8RAAAB
200 /js/rangy/rangy-serializer.js
200 /js/rangy/rangy-highlighter.js
200 /js/rangy/rangy-core.js
200 /image/loader.GIF
200 /socket.io/?EIO=3&transport=polling&t=MZAMQVI&sid=cp85-VT8GiJ_dF8RAAAB
200 /js/index.js
200 /cordova.js
200 /socket.io/?EIO=3&transport=polling&t=MZAMQdx
200 /img/logo.png
200 /js/images/ajax-loader.gif
 [cycle2] --c2 init--
200 /socket.io/?EIO=3&transport=polling&t=MZAMQ__&sid=yHFW-g8wwplx7IlXAAAC
 [cycle2] --c2 init--
200 /socket.io/?EIO=3&transport=polling&t=MZAMR0b&sid=yHFW-g8wwplx7IlXAAAC
 [cycle2] centerVert: true (boolean)
 [cycle2] centerHorz: true (boolean)
 [cycle2] timeout: 0 (number)
200 /socket.io/?EIO=3&transport=polling&t=MZAMR0n&sid=yHFW-g8wwplx7IlXAAAC
200 /appendixB.html
 [cycle2] centerVert: true (boolean)
 [cycle2] centerHorz: true (boolean)
 [cycle2] timeout: 0 (number)
200 /appendixB.html
200 /socket.io/?EIO=3&transport=polling&t=MZAMR0c&sid=yHFW-g8wwplx7IlXAAAC
200 /cordova_plugins.js
200 /plugins/cordova-plugin-device/src/browser/DeviceProxy.js
200 /plugins/cordova-plugin-file/www/DirectoryEntry.js
200 /plugins/cordova-plugin-file/www/DirectoryReader.js
200 /plugins/cordova-plugin-device/www/device.js
200 /plugins/cordova-plugin-dialogs/www/notification.js
200 /plugins/cordova-plugin-dialogs/www/browser/notification.js
200 /plugins/cordova-plugin-file/www/File.js
200 /plugins/cordova-plugin-file/www/Entry.js
200 /plugins/cordova-plugin-file/www/FileEntry.js
200 /plugins/cordova-plugin-file/www/FileError.js
200 /plugins/cordova-plugin-file/www/FileReader.js
200 /plugins/cordova-plugin-file/www/FileSystem.js
200 /plugins/cordova-plugin-file/www/FileUploadOptions.js
200 /plugins/cordova-plugin-file/www/FileWriter.js
200 /plugins/cordova-plugin-file/www/FileUploadResult.js
200 /plugins/cordova-plugin-file/www/Flags.js
200 /plugins/cordova-plugin-file/www/LocalFileSystem.js
200 /plugins/cordova-plugin-file/www/Metadata.js
200 /plugins/cordova-plugin-file/www/ProgressEvent.js
200 /plugins/cordova-plugin-file/www/fileSystems.js
200 /plugins/cordova-plugin-file/www/requestFileSystem.js
200 /plugins/cordova-plugin-file/www/resolveLocalFileSystemURI.js
200 /plugins/cordova-plugin-file/www/browser/isChrome.js
200 /plugins/cordova-plugin-file/www/fileSystemPaths.js
200 /plugins/cordova-plugin-file/src/browser/FileProxy.js
200 /plugins/cordova-plugin-file/www/browser/FileSystem.js
200 /plugins/cordova-plugin-file/www/browser/Preparing.js
200 /plugins/cordova-plugin-file-transfer/www/FileTransferError.js
200 /plugins/cordova-plugin-file-transfer/www/FileTransfer.js
200 /plugins/cordova-plugin-inappbrowser/src/browser/InAppBrowserProxy.js
200 /plugins/cordova-plugin-inappbrowser/www/inappbrowser.js
200 /plugins/cordova-plugin-network-information/www/Connection.js
200 /plugins/cordova-plugin-network-information/www/network.js
200 /plugins/cordova-plugin-file-transfer/www/browser/FileTransfer.js
200 /plugins/cordova-plugin-network-information/src/browser/network.js
200 /plugins/cordova-plugin-media/www/browser/Media.js
200 /plugins/cordova-plugin-media/www/Media.js
200 /plugins/cordova-plugin-media/www/MediaError.js
200 /plugins/cordova-plugin-splashscreen/www/splashscreen.js
200 /plugins/cordova-plugin-splashscreen/src/browser/SplashScreenProxy.js
200 /plugins/cordova-plugin-statusbar/www/statusbar.js
200 /plugins/cordova-plugin-statusbar/src/browser/statusbar.js
200 /plugins/cordova-plugin-email/www/email_composer.js
200 /plugins/cordova-plugin-email/src/browser/EmailComposerProxy.js
 adding proxy for Device
 adding proxy for Device
 adding proxy for File
 adding proxy for File
 adding proxy for InAppBrowser
 adding proxy for InAppBrowser
 adding proxy for NetworkStatus
 adding proxy for NetworkStatus
 adding proxy for SplashScreen
 adding proxy for SplashScreen
 adding proxy for EmailComposer
 adding proxy for EmailComposer
 Persistent fs quota granted
 Persistent fs quota granted
 Error: exec proxy not found for :: StatusBar :: _ready
 Error: exec proxy not found for :: StatusBar :: _ready
200 /config.xml
404 /screen
 BIRMApp.GetVideos: Getting the videos.
 BIRMApp.GetVideos: Getting the videos.
 BIRMApp.GetFiles: Getting the specific files as called from the strongly typed function.
 BIRMApp.GetFiles: Getting the specific files as called from the strongly typed function.
 FileSystem.GetFiles: Getting the specific files in gov.dot.birm/Videos.
 FileSystem.GetFiles: Getting the specific files in gov.dot.birm/Videos.
 FileSystem.GetFiles: The root directory is /gov.dot.birm.
 FileSystem.GetFiles: The root directory is /gov.dot.birm.
 FileSystem.GetFiles: The EPUB directory is /gov.dot.birm/Videos.
 FileSystem.GetFiles: The EPUB directory is /gov.dot.birm/Videos.
starting app server...
listening on 152.122.117.68:3000
200 /socket.io/?EIO=3&transport=polling&t=MZAMzAD
200 /socket.io/?EIO=3&transport=polling&t=MZAMzv4
200 /socket.io/?EIO=3&transport=polling&t=MZAM-1v&sid=77u7d42c2xkSflgYAAAD
200 /socket.io/?EIO=3&transport=polling&t=MZAM-1z&sid=bGoLrUyTtlwktO2RAAAE
200 /
200 /
304 /socket.io/socket.io.js
200 /js/themeroller-birm.css
200 /css/index.css
200 /css/highlightPlugin.css
200 /css/jquery.mmenu.all.css
200 /js/jquery.mobile-1.4.5.css
200 /css/jquery.mobile.icons.min.css
200 /css/jquery.mmenu.themes.css
200 /css/pinchzoomer.min.css
200 /css/jquery-impromptu.css
200 /css/clean-blue.css
200 /css/BIRM-Custom.css
200 /css/glossary.css
200 /js/themeroller-birm.css
200 /css/jquery.mobile.icons.min.css
200 /css/index.css
200 /js/jquery.mobile-1.4.5.css
200 /css/jquery.mmenu.all.css
200 /css/highlightPlugin.css
200 /css/jquery.mmenu.themes.css
200 /css/pinchzoomer.min.css
200 /css/glossary.css
200 /css/BIRM-Custom.css
200 /css/clean-blue.css
200 /css/jquery-impromptu.css
200 /js/jquery.highlight-5.js
200 /js/jstorage.js
200 /js/highlight/HighLight.js
200 /js/json2.js
200 /js/jquery.mmenu.all.min.js
200 /js/jquery.mmenu.jquerymobile.min.js
200 /js/jquery.waitforimages.js
200 /js/jquery-2.1.3.js
200 /js/jquery.mousewheel.min.js
200 /js/jquery.hammer.min.js
200 /js/modernizr.min.js
200 /js/moment.js
200 /js/jquery.pinchzoomer.min.js
200 /js/TweenMax.min.js
200 /js/fastclick.js
200 /js/jquery.unveil.js
200 /js/jquery.simplemodal.js
200 /js/jquery.mobile-1.4.5.js
200 /js/jquery.cycle2.center.js
200 /js/jquery.cycle2.swipe.js
200 /js/jquery.cycle2.js
200 /js/FileSystem.js
200 /js/jquery.fileDownload.js
200 /js/jquery-impromptu.js
200 /js/BIRM.js
200 /js/Connection.js
200 /js/Download.js
200 /js/ImportExport.js
200 /js/simple-expand.js
200 /js/rangy/rangy-selectionsaverestore.js
304 /socket.io/socket.io.js
200 /js/rangy/rangy-classapplier.js
200 /socket.io/?EIO=3&transport=polling&t=MZAM-5R
200 /js/rangy/rangy-core.js
200 /js/rangy/rangy-highlighter.js
200 /js/rangy/rangy-serializer.js
200 /js/jstorage.js
200 /js/jquery.highlight-5.js
200 /js/highlight/HighLight.js
200 /js/json2.js
200 /js/jquery.mmenu.all.min.js
200 /js/jquery.mmenu.jquerymobile.min.js
200 /js/jquery-2.1.3.js
200 /js/jquery.waitforimages.js
200 /js/jquery.hammer.min.js
200 /js/jquery.mousewheel.min.js
200 /js/modernizr.min.js
200 /js/jquery.mobile-1.4.5.js
200 /js/TweenMax.min.js
200 /js/jquery.pinchzoomer.min.js
200 /js/fastclick.js
200 /js/moment.js
200 /js/jquery.unveil.js
200 /js/jquery.fileDownload.js
200 /js/jquery.cycle2.center.js
200 /js/jquery.cycle2.swipe.js
200 /js/jquery.cycle2.js
200 /js/jquery.simplemodal.js
200 /js/jquery-impromptu.js
200 /js/FileSystem.js
200 /js/BIRM.js
200 /js/Connection.js
200 /js/Download.js
200 /js/ImportExport.js
200 /js/simple-expand.js
200 /js/rangy/rangy-selectionsaverestore.js
200 /socket.io/?EIO=3&transport=polling&t=MZAM-Dv
200 /socket.io/?EIO=3&transport=polling&t=MZAM-Ef&sid=dHy2ZoaRRKd24bFQAAAF
200 /js/rangy/rangy-classapplier.js
200 /js/rangy/rangy-core.js
200 /js/rangy/rangy-highlighter.js
200 /js/rangy/rangy-serializer.js
200 /image/loader.GIF
200 /image/loader.GIF
200 /socket.io/?EIO=3&transport=polling&t=MZAM-JN&sid=B6xEwtFf3mQiaMONAAAG
 BIRMApp.LoadChapters: Preloading BIRM EPUB chapters.
200 /socket.io/?EIO=3&transport=polling&t=MZAM-Ja&sid=B6xEwtFf3mQiaMONAAAG
200 /js/index.js
200 /cordova.js
 BIRMApp.LoadChapters: Preloading BIRM EPUB chapters.
 BIRMApp.LoadVideos: Preloading BIRM videos.
200 /img/logo.png
200 /cordova.js
200 /js/index.js
200 /socket.io/?EIO=3&transport=polling&t=MZAM-L3
200 /socket.io/?EIO=3&transport=polling&t=MZAM-Ja.0&sid=B6xEwtFf3mQiaMONAAAG
200 /socket.io/?EIO=3&transport=polling&t=MZAM-LM
200 /img/logo.png
200 /js/images/ajax-loader.gif
200 /js/images/ajax-loader.gif
 [cycle2] --c2 init--
200 /appendixB.html
200 /socket.io/?EIO=3&transport=polling&t=MZAM-l8&sid=skoXJ0wLs6DIe1QnAAAI
200 /appendixB.html
200 /appendixB.html
 [cycle2] --c2 init--
200 /socket.io/?EIO=3&transport=polling&t=MZAM-ly&sid=skoXJ0wLs6DIe1QnAAAI
200 /socket.io/?EIO=3&transport=polling&t=MZAM-mg&sid=zqf8KuTKxbeJzdS6AAAH
 [cycle2] centerVert: true (boolean)
200 /cordova_plugins.js
200 /appendixB.html
 [cycle2] centerHorz: true (boolean)
 [cycle2] timeout: 0 (number)
 [cycle2] centerVert: true (boolean)
 [cycle2] centerHorz: true (boolean)
 [cycle2] timeout: 0 (number)
200 /socket.io/?EIO=3&transport=polling&t=MZAM-nM&sid=skoXJ0wLs6DIe1QnAAAI
200 /socket.io/?EIO=3&transport=polling&t=MZAM-ly.0&sid=skoXJ0wLs6DIe1QnAAAI
 [cycle2] --c2 init--
200 /socket.io/?EIO=3&transport=polling&t=MZAM-n_&sid=zqf8KuTKxbeJzdS6AAAH
200 /plugins/cordova-plugin-device/www/device.js
200 /plugins/cordova-plugin-device/src/browser/DeviceProxy.js
200 /plugins/cordova-plugin-dialogs/www/notification.js
200 /plugins/cordova-plugin-dialogs/www/browser/notification.js
200 /plugins/cordova-plugin-file/www/DirectoryEntry.js
200 /cordova_plugins.js
200 /plugins/cordova-plugin-file/www/DirectoryReader.js
200 /plugins/cordova-plugin-file/www/Entry.js
200 /plugins/cordova-plugin-file/www/File.js
200 /plugins/cordova-plugin-file/www/FileEntry.js
200 /plugins/cordova-plugin-file/www/FileError.js
200 /plugins/cordova-plugin-file/www/FileReader.js
 [cycle2] centerVert: true (boolean)
 [cycle2] centerHorz: true (boolean)
 [cycle2] timeout: 0 (number)
200 /socket.io/?EIO=3&transport=polling&t=MZAM-om&sid=zqf8KuTKxbeJzdS6AAAH
200 /plugins/cordova-plugin-file/www/FileSystem.js
200 /plugins/cordova-plugin-file/www/FileUploadOptions.js
200 /plugins/cordova-plugin-file/www/FileUploadResult.js
200 /plugins/cordova-plugin-file/www/FileWriter.js
200 /plugins/cordova-plugin-device/www/device.js
200 /plugins/cordova-plugin-file/www/Flags.js
200 /plugins/cordova-plugin-device/src/browser/DeviceProxy.js
200 /plugins/cordova-plugin-dialogs/www/browser/notification.js
200 /plugins/cordova-plugin-dialogs/www/notification.js
200 /plugins/cordova-plugin-file/www/LocalFileSystem.js
200 /plugins/cordova-plugin-file/www/DirectoryEntry.js
200 /socket.io/?EIO=3&transport=polling&t=MZAM-o0&sid=zqf8KuTKxbeJzdS6AAAH
200 /plugins/cordova-plugin-file/www/Metadata.js
200 /plugins/cordova-plugin-file/www/ProgressEvent.js
200 /plugins/cordova-plugin-file/www/fileSystems.js
200 /plugins/cordova-plugin-file/www/requestFileSystem.js
200 /plugins/cordova-plugin-file/www/DirectoryReader.js
200 /plugins/cordova-plugin-file/www/resolveLocalFileSystemURI.js
200 /plugins/cordova-plugin-file/www/Entry.js
200 /plugins/cordova-plugin-file/www/File.js
200 /plugins/cordova-plugin-file/www/FileEntry.js
200 /plugins/cordova-plugin-file/www/browser/isChrome.js
200 /plugins/cordova-plugin-file/www/FileReader.js
200 /plugins/cordova-plugin-file/www/FileError.js
200 /plugins/cordova-plugin-file/www/browser/Preparing.js
200 /plugins/cordova-plugin-file/www/fileSystemPaths.js
200 /plugins/cordova-plugin-file/src/browser/FileProxy.js
200 /plugins/cordova-plugin-file/www/FileSystem.js
200 /plugins/cordova-plugin-file/www/browser/FileSystem.js
200 /plugins/cordova-plugin-file-transfer/www/FileTransferError.js
200 /plugins/cordova-plugin-file/www/FileUploadOptions.js
200 /plugins/cordova-plugin-file/www/FileUploadResult.js
200 /plugins/cordova-plugin-file/www/FileWriter.js
200 /plugins/cordova-plugin-file-transfer/www/FileTransfer.js
200 /plugins/cordova-plugin-file/www/Flags.js
200 /plugins/cordova-plugin-file/www/LocalFileSystem.js
200 /plugins/cordova-plugin-file-transfer/www/browser/FileTransfer.js
200 /plugins/cordova-plugin-inappbrowser/www/inappbrowser.js
200 /plugins/cordova-plugin-file/www/Metadata.js
200 /plugins/cordova-plugin-inappbrowser/src/browser/InAppBrowserProxy.js
200 /plugins/cordova-plugin-network-information/www/network.js
200 /plugins/cordova-plugin-network-information/www/Connection.js
200 /plugins/cordova-plugin-file/www/ProgressEvent.js
200 /plugins/cordova-plugin-file/www/fileSystems.js
200 /plugins/cordova-plugin-file/www/requestFileSystem.js
200 /plugins/cordova-plugin-network-information/src/browser/network.js
200 /plugins/cordova-plugin-file/www/resolveLocalFileSystemURI.js
200 /plugins/cordova-plugin-file/www/browser/isChrome.js
200 /plugins/cordova-plugin-file/www/browser/Preparing.js
200 /plugins/cordova-plugin-media/www/MediaError.js
200 /plugins/cordova-plugin-media/www/browser/Media.js
200 /plugins/cordova-plugin-media/www/Media.js
200 /plugins/cordova-plugin-splashscreen/www/splashscreen.js
200 /plugins/cordova-plugin-splashscreen/src/browser/SplashScreenProxy.js
200 /plugins/cordova-plugin-file/www/fileSystemPaths.js
200 /plugins/cordova-plugin-file/www/browser/FileSystem.js
200 /plugins/cordova-plugin-statusbar/www/statusbar.js
200 /plugins/cordova-plugin-file-transfer/www/FileTransferError.js
200 /plugins/cordova-plugin-file/src/browser/FileProxy.js
200 /plugins/cordova-plugin-file-transfer/www/FileTransfer.js
200 /plugins/cordova-plugin-file-transfer/www/browser/FileTransfer.js
200 /plugins/cordova-plugin-statusbar/src/browser/statusbar.js
200 /plugins/cordova-plugin-email/www/email_composer.js
200 /plugins/cordova-plugin-email/src/browser/EmailComposerProxy.js
200 /plugins/cordova-plugin-inappbrowser/www/inappbrowser.js
200 /plugins/cordova-plugin-network-information/www/network.js
200 /plugins/cordova-plugin-network-information/www/Connection.js
200 /plugins/cordova-plugin-inappbrowser/src/browser/InAppBrowserProxy.js
200 /plugins/cordova-plugin-network-information/src/browser/network.js
200 /plugins/cordova-plugin-media/www/MediaError.js
 adding proxy for Device
 adding proxy for Device
200 /plugins/cordova-plugin-media/www/Media.js
 BIRMApp.LoadVideos: Preloading BIRM videos.
 adding proxy for File
 adding proxy for File
200 /plugins/cordova-plugin-media/www/browser/Media.js
200 /plugins/cordova-plugin-splashscreen/www/splashscreen.js
200 /plugins/cordova-plugin-splashscreen/src/browser/SplashScreenProxy.js
200 /plugins/cordova-plugin-statusbar/src/browser/statusbar.js
200 /plugins/cordova-plugin-statusbar/www/statusbar.js
 [cycle2] --c2 init--
 adding proxy for InAppBrowser
 adding proxy for InAppBrowser
200 /config.xml
200 /plugins/cordova-plugin-email/www/email_composer.js
200 /plugins/cordova-plugin-email/src/browser/EmailComposerProxy.js
 [cycle2] centerVert: true (boolean)
 adding proxy for NetworkStatus
 adding proxy for NetworkStatus
 [cycle2] centerHorz: true (boolean)
 adding proxy for SplashScreen
 adding proxy for SplashScreen
 [cycle2] timeout: 0 (number)
 adding proxy for EmailComposer
 adding proxy for EmailComposer
 adding proxy for Device
 adding proxy for Device
404 /screen
 Persistent fs quota granted
 Persistent fs quota granted
 Error: exec proxy not found for :: StatusBar :: _ready
 Error: exec proxy not found for :: StatusBar :: _ready
200 /config.xml
404 /screen
 adding proxy for File
 adding proxy for File
 adding proxy for InAppBrowser
 adding proxy for InAppBrowser
 adding proxy for NetworkStatus
 adding proxy for NetworkStatus
 adding proxy for SplashScreen
 adding proxy for SplashScreen
 adding proxy for EmailComposer
 adding proxy for EmailComposer
 Persistent fs quota granted
 Persistent fs quota granted
 Error: exec proxy not found for :: StatusBar :: _ready
 Error: exec proxy not found for :: StatusBar :: _ready

**Comment by awilsondot** [comment]
Deleted plugins folder, cleared browser cached, even tried a different browser and got the same behavior. Old code is running.

**Comment by awilsondot** [comment]
Also created a copy of the application in another folder and added to PhoneGap Desktop as a different app, same behavior, old code is running.

**Comment by csp567** [comment]
I am facing the same issue. Any Solution on this?

**Comment by csp567** [comment]
> @NirBentzy I'll recomend deleting the plugins folder and restart the server, it will force the download of the plugins again and if any of them fail to load, it's probably an incompatibility with that particular plugin.

Still not working tried a few other solutions but still facing the same issue.

**Comment by ErandaMethmal** [comment]
Tried following,

- Incognito mode
- Restarting the computer
- Clearing browser cache
- In separate browsers (Safari, chrome, firefox) 
- Changing the IDE (VS Code, Atom)
- Cloned the project in to different locations

Note : Previously this error was solved by cloning the project and restarting the computer. but this time it is not working.

**Comment by fuzzyTew** [comment]
I noted I was changing www/index.html and platforms/browser/www/index.html was not changing and was being loaded.  I did `phonegap platform remove browser` and am just serving straight from www/ now, which is working for me with my basic code.
